package report

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/stormbane-security/beacon/internal/finding"
)

// pocEntry pairs a finding with its generated PoC filename.
type pocEntry struct {
	Finding  finding.Finding
	Filename string
}

// RenderPoCBundle generates individual PoC files for each finding and an
// index.html that links to them. All files are written into outDir, which
// is created if it does not exist.
func RenderPoCBundle(findings []finding.Finding, outDir string) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("create poc directory: %w", err)
	}

	var entries []pocEntry
	usedNames := make(map[string]int)

	for _, f := range findings {
		content, filename, err := GeneratePoC(f)
		if err != nil {
			continue // skip findings that can't produce a PoC
		}

		// Deduplicate filenames by appending a counter.
		if n, exists := usedNames[filename]; exists {
			usedNames[filename] = n + 1
			ext := filepath.Ext(filename)
			base := strings.TrimSuffix(filename, ext)
			filename = fmt.Sprintf("%s-%d%s", base, n+1, ext)
		} else {
			usedNames[filename] = 1
		}

		path := filepath.Join(outDir, filename)
		if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
			return fmt.Errorf("write poc file %s: %w", filename, err)
		}

		entries = append(entries, pocEntry{Finding: f, Filename: filename})
	}

	// Build index.html
	indexHTML := renderPoCIndex(entries)
	indexPath := filepath.Join(outDir, "index.html")
	if err := os.WriteFile(indexPath, []byte(indexHTML), 0o600); err != nil {
		return fmt.Errorf("write poc index: %w", err)
	}

	return nil
}

func renderPoCIndex(entries []pocEntry) string {
	var b strings.Builder

	b.WriteString(`<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Beacon PoC Bundle</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", monospace; margin: 2em; background: #0a0a1a; color: #e0e0e0; }
        h1 { color: #e94560; }
        table { border-collapse: collapse; width: 100%; margin-top: 1em; }
        th, td { text-align: left; padding: 0.6em 1em; border-bottom: 1px solid #222; }
        th { background: #16213e; color: #4ecca3; }
        tr:hover { background: #16213e; }
        a { color: #e94560; text-decoration: none; }
        a:hover { text-decoration: underline; }
        .severity-critical { color: #ff2e63; font-weight: bold; }
        .severity-high { color: #ff6b35; font-weight: bold; }
        .severity-medium { color: #ffc107; }
        .severity-low { color: #4ecca3; }
        .severity-info { color: #888; }
        .meta { color: #888; margin-bottom: 1em; }
    </style>
</head>
<body>
    <h1>Beacon Proof-of-Concept Bundle</h1>
`)

	fmt.Fprintf(&b, "    <p class=\"meta\">Generated: %s | Findings: %d</p>\n",
		time.Now().Format("2006-01-02 15:04 MST"), len(entries))

	if len(entries) == 0 {
		b.WriteString("    <p>No findings produced PoC files.</p>\n")
	} else {
		b.WriteString(`    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Severity</th>
                <th>Check ID</th>
                <th>Asset</th>
                <th>Title</th>
                <th>PoC File</th>
            </tr>
        </thead>
        <tbody>
`)
		for i, e := range entries {
			sevClass := "severity-" + strings.ToLower(SeverityLabel(e.Finding.Severity))
			fmt.Fprintf(&b, `            <tr>
                <td>%d</td>
                <td class="%s">%s</td>
                <td>%s</td>
                <td>%s</td>
                <td>%s</td>
                <td><a href="%s">%s</a></td>
            </tr>
`, i+1, sevClass, SeverityLabel(e.Finding.Severity), e.Finding.CheckID, escapeHTML(e.Finding.Asset), escapeHTML(e.Finding.Title), e.Filename, e.Filename)
		}
		b.WriteString("        </tbody>\n    </table>\n")
	}

	b.WriteString(`
    <p class="meta" style="margin-top: 2em;">
        Generated by <strong>Beacon</strong> — attack surface scanner.<br>
        These PoCs are for authorized security testing only.
    </p>
</body>
</html>
`)
	return b.String()
}
