package finding

// ComplianceTags returns the compliance framework control IDs that a given
// CheckID maps to. Returns nil if the check has no specific compliance mapping.
//
// Frameworks mapped:
//   - SOC2 Trust Service Criteria (CC6.x, CC7.x, CC8.x, CC9.x)
//   - PCI DSS v4.0 (1.x–12.x)
//   - NIST CSF (PR.AC, PR.DS, PR.IP, PR.PT, DE.AE)
//   - HIPAA Security Rule (164.3xx)
//   - ISO 27001:2022 Annex A (A.x.x)
func ComplianceTags(id CheckID) []string {
	if tags, ok := complianceMap[id]; ok {
		return tags
	}
	return nil
}

var complianceMap = map[CheckID][]string{

	// ── Email Security ──────────────────────────────────────────────────────
	CheckEmailSPFMissing:            {"SOC2-CC6.1", "NIST-PR.IP"},
	CheckEmailSPFSoftfail:           {"SOC2-CC6.1"},
	CheckEmailSPFLookupLimit:        {"SOC2-CC6.1"},
	CheckEmailDMARCMissing:          {"SOC2-CC6.1", "NIST-PR.IP", "ISO27001-A.13.2"},
	CheckEmailDMARCPolicyNone:       {"SOC2-CC6.1", "ISO27001-A.13.2"},
	CheckEmailDMARCSubdomainNone:    {"SOC2-CC6.1", "ISO27001-A.13.2"},
	CheckEmailDMARCNoReporting:      {"SOC2-CC6.1"},
	CheckEmailDKIMMissing:           {"SOC2-CC6.1", "NIST-PR.IP"},
	CheckEmailDKIMWeakKey:           {"SOC2-CC6.7", "NIST-PR.IP"},
	CheckEmailMTASTSMissing:         {"SOC2-CC6.7", "NIST-PR.DS"},
	CheckEmailMTASTSNotEnforced:     {"SOC2-CC6.7"},
	CheckEmailMTASTSPolicyFetchFail: {"SOC2-CC6.7"},
	CheckEmailTLSRPTMissing:         {"SOC2-CC6.7"},
	CheckEmailDANEMissing:           {"SOC2-CC6.7"},
	CheckEmailSpoofable:             {"SOC2-CC6.1", "PCI-12.10", "HIPAA-164.308(a)(5)"},
	CheckEmailSMTPOpenRelay:         {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},
	CheckEmailSMTPBannerLeak:        {"SOC2-CC6.6"},

	// ── TLS / SSL ───────────────────────────────────────────────────────────
	CheckTLSCertExpiry7d:          {"SOC2-CC9.1", "PCI-4.2.1"},
	CheckTLSCertExpiry30d:         {"SOC2-CC9.1", "PCI-4.2.1"},
	CheckTLSCertSelfSigned:        {"SOC2-CC6.7", "PCI-4.2.1", "HIPAA-164.312(e)(2)"},
	CheckTLSCertHostnameMismatch:  {"SOC2-CC6.7", "PCI-4.2.1"},
	CheckTLSCertChainInvalid:      {"SOC2-CC6.7", "PCI-4.2.1"},
	CheckTLSProtocolSSLv2:         {"PCI-4.2.1", "SOC2-CC6.7", "HIPAA-164.312(e)(2)"},
	CheckTLSProtocolSSLv3:         {"PCI-4.2.1", "SOC2-CC6.7", "HIPAA-164.312(e)(2)"},
	CheckTLSProtocolTLS10:         {"PCI-4.2.1", "SOC2-CC6.7"},
	CheckTLSProtocolTLS11:         {"PCI-4.2.1", "SOC2-CC6.7"},
	CheckTLSWeakCipher:            {"PCI-4.2.1", "SOC2-CC6.7", "HIPAA-164.312(e)(2)"},
	CheckTLSBEAST:                 {"PCI-4.2.1", "SOC2-CC6.7"},
	CheckTLSHeartbleed:            {"PCI-6.3.3", "SOC2-CC6.6"},
	CheckTLSPOODLE:                {"PCI-6.3.3", "SOC2-CC6.7"},
	CheckTLSROBOT:                 {"PCI-6.3.3"},
	CheckTLSCCSInjection:          {"PCI-6.3.3", "SOC2-CC6.6"},
	CheckTLSCertWeakKey:           {"SOC2-CC6.7", "PCI-4.2.1", "NIST-PR.DS"},
	CheckTLSCertWeakSignature:     {"SOC2-CC6.7", "PCI-4.2.1"},
	CheckTLSCertRevoked:           {"SOC2-CC6.7", "PCI-4.2.1"},
	CheckTLSNoPFS:                 {"SOC2-CC6.7", "PCI-4.2.1", "NIST-PR.DS"},
	CheckTLSMixedContent:          {"SOC2-CC6.7", "PCI-4.2.1"},
	CheckTLSNoSecureRenegotiation: {"SOC2-CC6.7", "PCI-4.2.1"},
	CheckTLSCertSANMissing:        {"SOC2-CC6.7"},
	CheckTLSHSTSShortMaxAge:       {"SOC2-CC6.7"},

	// ── DNS Security ────────────────────────────────────────────────────────
	CheckDNSAXFRAllowed:   {"SOC2-CC6.1", "ISO27001-A.12.4"},
	CheckDNSWildcard:      {"SOC2-CC6.6"},
	CheckDNSDanglingCNAME: {"SOC2-CC6.6", "NIST-PR.IP"},
	CheckDNSMissingCAA:    {"SOC2-CC6.7"},
	CheckDNSDNSSECMissing: {"SOC2-CC6.7", "NIST-PR.DS"},

	// ── HTTP Security Headers ───────────────────────────────────────────────
	CheckHeadersMissingCSP:               {"SOC2-CC6.6", "PCI-6.4.1", "NIST-PR.IP"},
	CheckHeadersMissingHSTS:              {"SOC2-CC6.7", "PCI-4.2.1", "NIST-PR.DS"},
	CheckHeadersMissingXFrameOptions:     {"SOC2-CC6.6", "PCI-6.4.1"},
	CheckHeadersMissingXContentType:      {"SOC2-CC6.6", "PCI-6.4.1"},
	CheckHeadersMissingReferrerPolicy:    {"SOC2-CC6.6"},
	CheckHeadersMissingPermissionsPolicy: {"SOC2-CC6.6"},
	CheckHeadersServerInfoLeak:           {"SOC2-CC6.6", "PCI-6.4"},

	// ── Exposure / Misconfiguration ─────────────────────────────────────────
	CheckExposureHTTPNoRedirect:   {"SOC2-CC6.7", "PCI-4.2.1"},
	CheckExposureStagingSubdomain: {"SOC2-CC6.6", "PCI-6.4"},
	CheckExposureAdminPath:        {"SOC2-CC6.6", "PCI-6.4"},
	CheckExposureRobotsLeak:       {"SOC2-CC6.6"},
	CheckExposureEnvFile:          {"SOC2-CC6.1", "PCI-6.3.1", "HIPAA-164.312(a)(1)"},
	CheckExposureGitExposed:       {"SOC2-CC6.1", "PCI-6.3.1"},
	CheckExposureBackupFile:       {"SOC2-CC6.1", "PCI-6.3.1"},
	CheckExposureAPIDocs:          {"SOC2-CC6.6"},
	CheckExposureMonitoringPanel:  {"SOC2-CC6.6"},
	CheckExposureCICDPanel:        {"SOC2-CC8.1", "PCI-6.3"},
	CheckExposureSpringActuator:   {"SOC2-CC6.6", "PCI-6.4"},
	CheckExposureCloudStorage:     {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.DS"},
	CheckExposureSensitiveFile:    {"SOC2-CC6.1", "PCI-6.3.1"},

	// ── Subdomain / Domain ──────────────────────────────────────────────────
	CheckSubdomainTakeover: {"SOC2-CC6.6", "NIST-PR.IP"},
	CheckDomainTyposquat:   {"SOC2-CC6.6"},

	// ── Web Application Security ────────────────────────────────────────────
	CheckWebXSS:                    {"PCI-6.4.1", "SOC2-CC6.6"},
	CheckWebSQLi:                   {"PCI-6.4.1", "SOC2-CC6.6", "HIPAA-164.312(a)(1)"},
	CheckWebOpenRedirect:           {"SOC2-CC6.6", "PCI-6.4.1"},
	CheckWebSSRF:                   {"PCI-6.4.1", "SOC2-CC6.6", "NIST-PR.AC"},
	CheckWebPathTraversal:          {"PCI-6.4.1", "SOC2-CC6.6", "HIPAA-164.312(a)(1)"},
	CheckWebDefaultCredentials:     {"PCI-8.3.9", "SOC2-CC6.2"},
	CheckWebHTTPRequestSmuggling:   {"PCI-6.4.1", "SOC2-CC6.6"},
	CheckWebDangerousMethodEnabled: {"SOC2-CC6.6", "PCI-6.4"},
	CheckSecretInResponseHeader:    {"SOC2-CC6.1", "PCI-6.3.1"},
	CheckWebDebugEndpoint:          {"SOC2-CC6.6", "PCI-6.4"},
	CheckWebErrorInfoLeak:          {"SOC2-CC6.6", "PCI-6.4"},
	CheckWebSSTI:                   {"PCI-6.4.1", "SOC2-CC6.6"},
	CheckWebCRLFInjection:          {"PCI-6.4.1", "SOC2-CC6.6"},
	CheckWebPrototypePollution:     {"PCI-6.4.1", "SOC2-CC6.6"},
	CheckWebXXE:                    {"PCI-6.4.1", "SOC2-CC6.6"},
	CheckWebInsecureDeserialize:    {"PCI-6.4.1", "SOC2-CC6.6"},
	CheckWebDotNetDeserialize:      {"PCI-6.4.1", "SOC2-CC6.6"},
	CheckWebSSRFRedirectMetadata:   {"PCI-6.4.1", "SOC2-CC6.6", "NIST-PR.AC"},
	CheckWebHPP:                    {"PCI-6.4.1", "SOC2-CC6.6"},
	CheckWebNginxAliasTraversal:    {"PCI-6.4.1", "SOC2-CC6.6"},
	CheckWebIISShortname:           {"SOC2-CC6.6"},
	CheckWebFileUpload:             {"PCI-6.4.1", "SOC2-CC6.6"},
	CheckHTTPClickjacking:          {"PCI-6.4.1", "SOC2-CC6.6"},
	CheckWebSocketCSWSH:            {"PCI-6.4.1", "SOC2-CC6.6"},
	CheckHostHeaderInjection:       {"PCI-6.4.1", "SOC2-CC6.6"},
	CheckSwaggerExposed:            {"SOC2-CC6.6"},

	// ── CORS ────────────────────────────────────────────────────────────────
	CheckCORSMisconfiguration:       {"PCI-6.4.1", "SOC2-CC6.6"},
	CheckCORSNullOrigin:             {"PCI-6.4.1", "SOC2-CC6.6"},
	CheckCORSPreflightMisconfig:     {"PCI-6.4.1", "SOC2-CC6.6"},
	CheckCORSCredentialedReflection: {"PCI-6.4.1", "SOC2-CC6.6", "NIST-PR.AC"},

	// ── Cookies ─────────────────────────────────────────────────────────────
	CheckCookieMissingSecure:   {"SOC2-CC6.7", "PCI-4.2.1"},
	CheckCookieMissingHTTPOnly: {"SOC2-CC6.6", "PCI-6.4.1"},
	CheckCookieMissingSameSite: {"SOC2-CC6.6", "PCI-6.4.1"},

	// ── CSP ─────────────────────────────────────────────────────────────────
	CheckCSPUnsafeInline:   {"SOC2-CC6.6", "PCI-6.4.1"},
	CheckCSPUnsafeEval:     {"SOC2-CC6.6", "PCI-6.4.1"},
	CheckCSPWildcardSource: {"SOC2-CC6.6", "PCI-6.4.1"},

	// ── WAF ─────────────────────────────────────────────────────────────────
	CheckWAFOriginExposed:  {"SOC2-CC6.6", "PCI-1.3"},
	CheckWAFBypassHeader:   {"SOC2-CC6.6", "PCI-1.3"},
	CheckWAFInsecureMode:   {"SOC2-CC6.7", "PCI-4.2.1"},

	// ── DLP ─────────────────────────────────────────────────────────────────
	CheckDLPSSN:           {"HIPAA-164.312", "PCI-3.4", "SOC2-CC6.1"},
	CheckDLPCreditCard:    {"PCI-3.4", "PCI-3.5", "SOC2-CC6.1"},
	CheckDLPDatabaseURL:   {"SOC2-CC6.1", "PCI-6.3.1"},
	CheckDLPPrivateKey:    {"SOC2-CC6.1", "PCI-6.3.1"},
	CheckDLPAPIKey:        {"SOC2-CC6.1", "PCI-6.3.1"},
	CheckDLPEmailList:     {"HIPAA-164.312", "SOC2-CC6.1"},
	CheckDLPVision:        {"PCI-3.4", "HIPAA-164.312"},
	CheckVisionServiceID:  {"SOC2-CC6.6"},
	CheckDLPWifiCredential: {"SOC2-CC6.1", "PCI-6.3.1"},

	// ── JS Content Analysis ─────────────────────────────────────────────────
	CheckJSHardcodedSecret:  {"SOC2-CC6.1", "PCI-6.3.1"},
	CheckJSInternalEndpoint: {"SOC2-CC6.6"},
	CheckJSSourceMapExposed: {"SOC2-CC6.6", "PCI-6.3.1"},

	// ── Cloud Storage Buckets ───────────────────────────────────────────────
	CheckCloudBucketPublic:   {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.DS"},
	CheckCloudBucketWritable: {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.DS"},
	CheckNucleiS3BucketExposed:   {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.DS"},
	CheckNucleiMisconfiguredCORS: {"PCI-6.4.1", "SOC2-CC6.6"},

	// ── Port / Service Exposure ─────────────────────────────────────────────
	CheckPortRedisUnauth:           {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},
	CheckPortElasticsearchUnauth:   {"SOC2-CC6.6", "PCI-1.3", "HIPAA-164.312"},
	CheckPortPrometheusUnauth:      {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortDockerUnauth:          {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},
	CheckPortKubeletUnauth:         {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},
	CheckPortMemcachedUnauth:       {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortJupyterExposed:        {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortCouchDBUnauth:         {"SOC2-CC6.6", "PCI-1.3", "HIPAA-164.312"},
	CheckPortSSHExposed:            {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortRDPExposed:            {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},
	CheckPortVNCExposed:            {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},
	CheckPortTelnetExposed:         {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},
	CheckPortFTPExposed:            {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortFTPAnonymous:          {"SOC2-CC6.2", "PCI-1.3", "NIST-PR.AC"},
	CheckPortFTPVsftpdBackdoor:     {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckPortSMBExposed:            {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortSMBNullSession:        {"SOC2-CC6.2", "PCI-1.3", "NIST-PR.AC"},
	CheckPortSMBv1Enabled:          {"SOC2-CC6.6", "PCI-1.3", "PCI-6.3.3"},
	CheckPortDatabaseExposed:       {"SOC2-CC6.6", "PCI-1.3", "HIPAA-164.312"},
	CheckPortK8sAPIExposed:         {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},
	CheckPortWinRMExposed:          {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},
	CheckPortAMQPExposed:           {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortKafkaExposed:          {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortZooKeeperExposed:      {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortInfluxDBExposed:       {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortSplunkMgmtExposed:     {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortCiscoSmartInstall:     {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},
	CheckPortHuggingFaceTGIExposed: {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortAutomatic1111Exposed:  {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortNacosExposed:          {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},
	CheckPortConsulNoACL:           {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},
	CheckPortNiFiExposed:           {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortOllamaExposed:         {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortRabbitMQMgmtExposed:   {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortTektonDashboardExposed: {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortHarborExposed:          {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},
	CheckPortArgoCDExposed:          {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortAirflowExposed:         {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortOpenWebUIExposed:       {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortPulsarAdminExposed:     {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortSGLangExposed:          {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortAdGuardExposed:         {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortStepCAExposed:          {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},
	CheckPortArtifactoryExposed:     {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},
	CheckPortNexusExposed:           {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},
	CheckPortGRPCReflectionEnabled:  {"SOC2-CC6.6", "NIST-PR.IP"},
	CheckPortDevServerExposed:       {"SOC2-CC6.6", "PCI-6.4"},
	CheckPortGradioExposed:          {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortWebminExposed:          {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortWazuhAPIExposed:        {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortSupersetExposed:        {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortMLflowExposed:          {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortRayDashboardExposed:    {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortNATSMonitoringExposed:  {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortClickHouseExposed:      {"SOC2-CC6.6", "PCI-1.3", "HIPAA-164.312"},
	CheckPortBGPExposed:             {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortMinIODefaultCreds:      {"SOC2-CC6.2", "PCI-8.3.9", "NIST-PR.AC"},

	// ── Port — default credentials ──────────────────────────────────────────
	CheckPortRabbitMQDefaultCreds: {"SOC2-CC6.2", "PCI-8.3.9", "NIST-PR.AC"},
	CheckPortMySQLNoAuth:          {"SOC2-CC6.2", "PCI-8.3.9", "HIPAA-164.312(a)(1)", "NIST-PR.AC"},
	CheckPortPostgreSQLTrust:      {"SOC2-CC6.2", "PCI-8.3.9", "HIPAA-164.312(a)(1)", "NIST-PR.AC"},
	CheckPortMSSQLDefaultCreds:    {"SOC2-CC6.2", "PCI-8.3.9", "HIPAA-164.312(a)(1)", "NIST-PR.AC"},

	// ── Email / messaging port exposure ─────────────────────────────────────
	CheckPortSMTPExposed:       {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortIMAPExposed:       {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortPOP3Exposed:       {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortSMTPOpenRelay:     {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},
	CheckPortExImVulnerable:    {"PCI-6.3.3", "SOC2-CC6.6"},

	// ── Directory services ──────────────────────────────────────────────────
	CheckPortLDAPExposed:            {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},
	CheckPortActiveDirectoryExposed: {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},
	CheckPortKerberosExposed:        {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},
	CheckPortGlobalCatalogExposed:   {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},

	// ── NFS / RPC / SNMP ────────────────────────────────────────────────────
	CheckPortRPCBindExposed:         {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortNFSExportsExposed:      {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},
	CheckPortSNMPPublicCommunity:    {"SOC2-CC6.2", "PCI-1.3", "NIST-PR.AC"},
	CheckPortSNMPWritableCommunity:  {"SOC2-CC6.2", "PCI-1.3", "NIST-PR.AC"},
	CheckPortEPMDExposed:            {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortWINSExposed:            {"SOC2-CC6.6", "PCI-1.3"},

	// ── UDP service exposure ────────────────────────────────────────────────
	CheckPortNTPAmplification:   {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortTFTPAnonymous:      {"SOC2-CC6.2", "PCI-1.3", "NIST-PR.AC"},
	CheckPortSSDPExposed:        {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortIKEExposed:         {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortNetBIOSNSExposed:   {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortMDNSExposed:        {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortDNSOpenResolver:    {"SOC2-CC6.6", "PCI-1.3"},

	// ── ICS / SCADA / OT ────────────────────────────────────────────────────
	CheckPortModbusExposed:     {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},
	CheckPortS7CommExposed:     {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},
	CheckPortEtherNetIPExposed: {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},
	CheckPortDNP3Exposed:       {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},
	CheckPortBACnetExposed:     {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortMQTTExposed:       {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},
	CheckPortSIPExposed:        {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortRTSPExposed:       {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortIPPExposed:        {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortISCSIExposed:      {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.DS"},
	CheckPortNetconfExposed:    {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortWinboxExposed:     {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortJetDirectExposed:  {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortMikroTikAPIExposed: {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortCheckPointExposed:  {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortNeo4jExposed:       {"SOC2-CC6.6", "PCI-1.3", "HIPAA-164.312"},
	CheckPortAsteriskAMIExposed: {"SOC2-CC6.6", "PCI-1.3"},

	// ── GraphQL ─────────────────────────────────────────────────────────────
	CheckGraphQLIntrospection:        {"SOC2-CC6.6", "NIST-PR.IP"},
	CheckGraphQLBatchQuery:           {"SOC2-CC6.6"},
	CheckGraphQLPersistedQueryBypass: {"SOC2-CC6.6"},
	CheckGraphQLGETEnabled:           {"SOC2-CC6.6", "PCI-6.4.1"},
	CheckGraphQLAliasDos:             {"SOC2-CC6.6"},

	// ── JWT ─────────────────────────────────────────────────────────────────
	CheckJWTWeakAlg:            {"SOC2-CC6.7", "PCI-4.2.1", "NIST-PR.DS"},
	CheckJWTLongExpiry:         {"SOC2-CC6.1", "NIST-PR.AC"},
	CheckJWTSensitivePayload:   {"SOC2-CC6.1", "PCI-3.4", "HIPAA-164.312"},
	CheckJWTAlgNoneVariant:     {"SOC2-CC6.7", "PCI-4.2.1", "NIST-PR.DS"},
	CheckJWTEmptySecret:        {"SOC2-CC6.7", "PCI-4.2.1"},
	CheckJWTKidInjection:       {"PCI-6.4.1", "SOC2-CC6.6"},
	CheckJWTNoVerification:     {"SOC2-CC6.7", "PCI-8.3.1", "NIST-PR.AC"},
	CheckJWTAlgorithmConfusion: {"SOC2-CC6.7", "PCI-4.2.1", "NIST-PR.DS"},
	CheckJWTAudienceMissing:    {"SOC2-CC6.1", "NIST-PR.AC"},
	CheckJWTIssuerNotValidated: {"SOC2-CC6.1", "NIST-PR.AC"},
	CheckJWTEncryptionMissing:  {"SOC2-CC6.7", "PCI-3.4"},
	CheckJWTReplayMissing:      {"SOC2-CC6.6", "NIST-PR.AC"},
	CheckJWKSWeakKey:           {"SOC2-CC6.7", "PCI-4.2.1"},
	CheckJWKSMissingKID:        {"SOC2-CC6.7"},

	// ── OAuth / OIDC ────────────────────────────────────────────────────────
	CheckOAuthMissingState:      {"SOC2-CC6.6", "PCI-6.4.1", "NIST-PR.AC"},
	CheckOAuthWeakState:         {"SOC2-CC6.6", "PCI-6.4.1"},
	CheckOAuthMissingPKCE:       {"SOC2-CC6.6", "NIST-PR.AC"},
	CheckOAuthOpenRedirect:      {"SOC2-CC6.6", "PCI-6.4.1"},
	CheckOAuthSubdomainBypass:   {"SOC2-CC6.6", "PCI-6.4.1"},
	CheckOAuthTokenLeakReferer:  {"SOC2-CC6.1", "PCI-6.3.1"},
	CheckOIDCImplicitFlow:       {"SOC2-CC6.6", "NIST-PR.AC"},
	CheckOAuthImplicitAccepted:  {"SOC2-CC6.6", "NIST-PR.AC"},
	CheckOIDCWeakSigningAlg:     {"SOC2-CC6.7", "PCI-4.2.1"},
	CheckOIDCMissingJWKSURI:     {"SOC2-CC6.7"},
	CheckOAuthTokenInFragment:   {"SOC2-CC6.1", "PCI-6.3.1"},
	CheckOAuthRefreshNotRotated: {"SOC2-CC6.1", "NIST-PR.AC"},
	CheckOAuthTokenLongExpiry:   {"SOC2-CC6.1", "NIST-PR.AC"},
	CheckOIDCBackchannelMissing: {"SOC2-CC6.6"},

	// ── SAML ────────────────────────────────────────────────────────────────
	CheckSAMLEndpointExposed:       {"SOC2-CC6.6"},
	CheckSAMLMetadataExposed:       {"SOC2-CC6.6"},
	CheckSAMLSignatureNotValidated: {"SOC2-CC6.7", "PCI-8.3.1", "NIST-PR.AC"},
	CheckSAMLXMLWrapping:           {"SOC2-CC6.7", "PCI-6.4.1"},
	CheckSAMLReplayAllowed:         {"SOC2-CC6.6", "NIST-PR.AC"},
	CheckSAMLIssuerNotValidated:    {"SOC2-CC6.1", "NIST-PR.AC"},
	CheckSAMLAudienceNotValidated:  {"SOC2-CC6.1", "NIST-PR.AC"},
	CheckSAMLXXEInjection:          {"PCI-6.4.1", "SOC2-CC6.6"},
	CheckSAMLOpenRedirect:          {"SOC2-CC6.6", "PCI-6.4.1"},

	// ── IAM / Identity Management ───────────────────────────────────────────
	CheckSCIMExposed:             {"SOC2-CC6.6", "NIST-PR.AC"},
	CheckSCIMUnauthenticated:     {"SOC2-CC6.2", "PCI-8.3.1", "NIST-PR.AC"},
	CheckOIDCUserinfoLeak:        {"SOC2-CC6.1", "HIPAA-164.312"},
	CheckOAuthIntrospectExposed:  {"SOC2-CC6.6", "NIST-PR.AC"},
	CheckOAuthDeviceFlowExposed:  {"SOC2-CC6.6"},
	CheckOAuthDynClientReg:       {"SOC2-CC6.6", "NIST-PR.AC"},
	CheckLDAPInjection:           {"PCI-6.4.1", "SOC2-CC6.6", "NIST-PR.AC"},
	CheckCloudMetadataSSRF:       {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},
	CheckIdentityProviderExposed: {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},
	CheckOAuthPKCEDowngrade:      {"SOC2-CC6.6", "NIST-PR.AC"},
	CheckOAuthClientSecretLeak:   {"SOC2-CC6.1", "PCI-6.3.1"},
	CheckIdentityRoleEscalation:  {"SOC2-CC6.3", "PCI-7.2", "NIST-PR.AC"},

	// ── API Security ────────────────────────────────────────────────────────
	CheckRateLimitMissing:      {"SOC2-CC6.6"},
	CheckRateLimitBypass:       {"SOC2-CC6.6"},

	// ── Dirbusting ──────────────────────────────────────────────────────────
	CheckDirbustFound: {"SOC2-CC6.6"},

	// ── GitHub Actions ──────────────────────────────────────────────────────
	CheckGHActionUnpinned:                    {"SOC2-CC8.1", "PCI-6.3", "NIST-PR.IP"},
	CheckGHActionPRTargetUnsafe:              {"SOC2-CC8.1", "PCI-6.4"},
	CheckGHActionScriptInjection:             {"SOC2-CC8.1", "PCI-6.4.1"},
	CheckGHActionOverpermissioned:            {"SOC2-CC6.3", "PCI-7.2"},
	CheckGHActionSecretsEchoed:               {"SOC2-CC6.1", "PCI-6.3.1"},
	CheckGHActionSelfHostedPublic:            {"SOC2-CC6.6", "PCI-1.3"},
	CheckGHActionWorkflowRunUnsafe:           {"SOC2-CC8.1", "PCI-6.4"},
	CheckGHActionGitHubEnvInjection:          {"SOC2-CC8.1", "PCI-6.4.1"},
	CheckGHActionSecretsInherit:              {"SOC2-CC6.3", "PCI-7.2"},
	CheckGHActionInsecureCommands:            {"SOC2-CC8.1", "PCI-6.4"},
	CheckGHActionBotConditionSpoofable:       {"SOC2-CC8.1"},
	CheckGHActionArtiPacked:                  {"SOC2-CC8.1", "PCI-6.3.1"},
	CheckGHActionCachePoisoning:              {"SOC2-CC8.1", "PCI-6.3"},
	CheckGHActionUnsignedRelease:             {"SOC2-CC7.2", "PCI-6.3"},
	CheckGHActionReusableWorkflowUnpinned:    {"SOC2-CC8.1", "PCI-6.3", "NIST-PR.IP"},
	CheckGHActionWorkflowDispatchInjection:   {"SOC2-CC8.1", "PCI-6.4.1"},
	CheckGHActionKnownCompromised:            {"SOC2-CC8.1", "PCI-6.3.3", "NIST-PR.IP"},
	CheckGHActionIssueCommentUnsafe:          {"SOC2-CC8.1", "PCI-6.4"},
	CheckGHActionAutoMerge:                   {"SOC2-CC8.1", "PCI-6.4"},
	CheckGHActionAutoApprove:                 {"SOC2-CC8.1", "PCI-6.4"},
	CheckGHActionScheduledWrite:              {"SOC2-CC8.1", "PCI-6.4"},
	CheckGHActionContinueOnErrorSecurity:     {"SOC2-CC8.1"},
	CheckGHActionMissingJobTimeout:           {"SOC2-CC8.1"},

	// ── GitHub Actions — OIDC vs long-lived credentials ─────────────────────
	CheckGHActionAWSLongLivedKey:        {"SOC2-CC6.1", "PCI-8.3.6", "NIST-PR.AC"},
	CheckGHActionGCPServiceAccountKey:   {"SOC2-CC6.1", "PCI-8.3.6", "NIST-PR.AC"},
	CheckGHActionAzureCredentials:       {"SOC2-CC6.1", "PCI-8.3.6", "NIST-PR.AC"},
	CheckGHActionNPMTokenNotOIDC:        {"SOC2-CC6.1", "PCI-8.3.6"},
	CheckGHActionPyPITokenNotTrusted:    {"SOC2-CC6.1", "PCI-8.3.6"},
	CheckGHActionDockerPasswordSecret:   {"SOC2-CC6.1", "PCI-8.3.6"},
	CheckGHActionPATUsedInWorkflow:      {"SOC2-CC6.1", "PCI-8.3.1", "NIST-PR.AC"},

	// ── GitHub Repository Configuration ─────────────────────────────────────
	CheckGitHubNoBranchProtection:      {"SOC2-CC8.1", "PCI-6.4"},
	CheckGitHubNoSecretScanning:        {"SOC2-CC6.1", "PCI-6.3.1"},
	CheckGitHubNoDependabot:            {"SOC2-CC6.6", "PCI-6.3.3"},
	CheckGitHubNoSAST:                  {"SOC2-CC6.6", "PCI-6.3"},
	CheckGitHubNoVulnAlerts:            {"SOC2-CC6.6", "PCI-6.3.3"},
	CheckGitHubForkWorkflowApproval:    {"SOC2-CC8.1", "PCI-6.4"},
	CheckGitHubDefaultTokenWrite:       {"SOC2-CC6.3", "PCI-7.2"},
	CheckGitHubActionsUnrestricted:     {"SOC2-CC8.1", "PCI-6.3"},
	CheckGitHubWebhookNoSecret:         {"SOC2-CC6.1", "PCI-6.3.1"},
	CheckGitHubOrgMFANotRequired:       {"SOC2-CC6.1", "PCI-8.4.2", "NIST-PR.AC"},
	CheckGitHubNoPushProtection:        {"SOC2-CC6.1", "PCI-6.3.1"},
	CheckGitHubNoSignedCommits:         {"SOC2-CC7.2"},
	CheckGitHubNoRequiredStatusChecks:  {"SOC2-CC8.1", "PCI-6.4"},
	CheckGitHubNoDependencyReview:      {"SOC2-CC6.6", "PCI-6.3.3"},
	CheckGitHubSecretInCode:            {"SOC2-CC6.1", "PCI-6.3.1", "NIST-PR.AC"},
	CheckGitHubPrivateKeyInRepo:        {"SOC2-CC6.1", "PCI-6.3.1"},
	CheckGitHubPackagePublic:           {"SOC2-CC6.6"},
	CheckGitHubNoCodeowners:            {"SOC2-CC8.1"},
	CheckGitHubNoTagProtection:         {"SOC2-CC7.2"},
	CheckGitHubNoEnvProtection:         {"SOC2-CC8.1", "PCI-6.4"},

	// ── CI/CD ───────────────────────────────────────────────────────────────
	CheckCICDUnpinnedAction:    {"SOC2-CC8.1", "PCI-6.3", "NIST-PR.IP"},
	CheckCICDScriptInjection:   {"SOC2-CC8.1", "PCI-6.4"},
	CheckCICDPwnRequest:        {"SOC2-CC8.1", "PCI-6.4"},
	CheckCICDBroadPermissions:  {"SOC2-CC6.3", "PCI-7.2"},
	CheckSecretsAPIKey:         {"SOC2-CC6.1", "PCI-6.3.1"},
	CheckCICDAttackPath:        {"SOC2-CC8.1", "PCI-6.4"},
	CheckDependencyConfusion:   {"SOC2-CC8.1", "PCI-6.3", "NIST-PR.IP"},
	CheckJenkinsGroovyRCE:      {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},

	// ── AI / LLM Security ───────────────────────────────────────────────────
	CheckAIEndpointExposed:   {"SOC2-CC6.6", "PCI-1.3"},
	CheckAIKeyExposed:        {"SOC2-CC6.1", "PCI-6.3.1"},
	CheckAIStreamingOpen:     {"SOC2-CC6.6", "PCI-1.3"},
	CheckAIPromptInjection:   {"SOC2-CC6.6", "PCI-6.4.1"},
	CheckAISystemLeak:        {"SOC2-CC6.1"},
	CheckAISSRFViaPLLM:       {"SOC2-CC6.6", "PCI-6.4.1", "NIST-PR.AC"},
	CheckAIDataExfil:         {"SOC2-CC6.1", "PCI-3.4", "HIPAA-164.312"},
	CheckAIToolAbuse:         {"SOC2-CC6.6", "PCI-6.4.1"},
	CheckAIIndirectInjection: {"SOC2-CC6.6", "PCI-6.4.1"},

	// ── Wireless ────────────────────────────────────────────────────────────
	CheckNetDeviceUniFiExposed:   {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},
	CheckCVEUniFiLog4Shell:       {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckNetDeviceTPLinkOmada:    {"SOC2-CC6.6", "PCI-1.3"},
	CheckCVETPLinkOmadaRCE:      {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckNetDeviceArubaInstant:   {"SOC2-CC6.6", "PCI-1.3"},
	CheckNetDeviceOpenWRTExposed: {"SOC2-CC6.6", "PCI-1.3"},
	CheckPortRADIUSExposed:       {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},
	CheckWiFiOpenNetwork:         {"PCI-1.3", "SOC2-CC6.6", "NIST-PR.AC", "ISO27001-A.13.1"},
	CheckWiFiWEPNetwork:          {"PCI-4.2.1", "SOC2-CC6.7", "NIST-PR.DS", "ISO27001-A.13.1"},
	CheckWiFiWPSEnabled:          {"PCI-4.2.1", "SOC2-CC6.7", "NIST-PR.AC"},
	CheckWiFiWPA2TKIP:            {"PCI-4.2.1", "SOC2-CC6.7"},
	CheckWiFiGatewayExposed:      {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},
	CheckWiFiPMKID:               {"PCI-4.2.1", "SOC2-CC6.7", "NIST-PR.DS"},

	// ── Network device BMC exposure ─────────────────────────────────────────
	CheckNetDeviceBMCExposed: {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},

	// ── Web3 / Blockchain ───────────────────────────────────────────────────
	CheckWeb3RPCEndpointExposed:   {"SOC2-CC6.6", "PCI-1.3"},
	CheckContractReentrancy:       {"SOC2-CC6.6"},
	CheckContractSelfDestruct:     {"SOC2-CC6.6"},
	CheckContractUncheckedCall:    {"SOC2-CC6.6"},
	CheckContractIntegerOverflow:  {"SOC2-CC6.6"},
	CheckContractProxyAdmin:       {"SOC2-CC6.3"},
	CheckChainNodeRPCExposed:      {"SOC2-CC6.6", "PCI-1.3"},
	CheckChainNodeUnauthorized:    {"SOC2-CC6.2", "PCI-1.3", "NIST-PR.AC"},
	CheckWeb3SIWEDomainBypass:     {"SOC2-CC6.6", "PCI-6.4.1"},
	CheckWeb3SIWENonceReuse:       {"SOC2-CC6.6", "NIST-PR.AC"},
	CheckWeb3SIWEReplay:           {"SOC2-CC6.6", "NIST-PR.AC"},
	CheckWeb3SIWEOverHTTP:         {"SOC2-CC6.7", "PCI-4.2.1"},
	CheckWeb3HorizontalEscalation: {"SOC2-CC6.3", "PCI-7.2", "NIST-PR.AC"},

	// ── Gateway / CDN / Infrastructure ──────────────────────────────────────
	CheckGatewayKongAdminExposed:    {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},
	CheckGatewayKongRouteEnum:       {"SOC2-CC6.6"},
	CheckGatewayHAProxyStatsExposed: {"SOC2-CC6.6", "PCI-1.3"},
	CheckGatewayNginxStatusExposed:  {"SOC2-CC6.6"},
	CheckGatewayVarnishDebugExposed: {"SOC2-CC6.6"},
	CheckGatewayTraefikAPIExposed:   {"SOC2-CC6.6", "PCI-1.3"},
	CheckGatewayEnvoyAdminExposed:   {"SOC2-CC6.6", "PCI-1.3"},
	CheckGatewayLinkerdVizExposed:   {"SOC2-CC6.6", "PCI-1.3"},
	CheckGatewayF5AdminExposed:      {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},
	CheckGatewayCitrixAdminExposed:  {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},
	CheckGatewayTykDashExposed:      {"SOC2-CC6.6", "PCI-1.3"},
	CheckCDNVarnishPurgeEnabled:     {"SOC2-CC6.6"},

	// ── Cloud — GCP ─────────────────────────────────────────────────────────
	CheckCloudGCPIAMPrimitiveRole:     {"SOC2-CC6.3", "PCI-7.2", "NIST-PR.AC", "ISO27001-A.9.2"},
	CheckCloudGCPServiceAccountKey:    {"SOC2-CC6.1", "PCI-8.3.1", "NIST-PR.AC"},
	CheckCloudGCPServiceAccountKeyOld: {"SOC2-CC6.1", "PCI-8.3.6", "NIST-PR.AC"},
	CheckCloudGCPBucketPublic:         {"SOC2-CC6.6", "PCI-1.3", "HIPAA-164.312(a)(1)", "NIST-PR.DS"},
	CheckCloudGCPComputeDefaultSA:     {"SOC2-CC6.3", "PCI-7.2", "NIST-PR.AC"},
	CheckCloudGCPGKEPublicEndpoint:    {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},
	CheckCloudGCPGKENoBinaryAuth:      {"SOC2-CC7.2", "PCI-6.3", "NIST-PR.DS"},

	// ── Cloud — AWS ─────────────────────────────────────────────────────────
	CheckCloudAWSIAMRootAccessKey:  {"SOC2-CC6.1", "PCI-8.3.1", "NIST-PR.AC", "ISO27001-A.9.2"},
	CheckCloudAWSIAMRootNoMFA:      {"SOC2-CC6.1", "PCI-8.4.2", "NIST-PR.AC", "ISO27001-A.9.4"},
	CheckCloudAWSIAMUserNoMFA:      {"SOC2-CC6.1", "PCI-8.4.2", "NIST-PR.AC"},
	CheckCloudAWSIAMAccessKeyOld:   {"SOC2-CC6.1", "PCI-8.3.6", "NIST-PR.AC"},
	CheckCloudAWSIAMPolicyWildcard: {"SOC2-CC6.3", "PCI-7.2", "NIST-PR.AC", "ISO27001-A.9.2"},
	CheckCloudAWSS3BucketPublic:    {"SOC2-CC6.6", "PCI-1.3", "HIPAA-164.312(a)(1)", "NIST-PR.DS"},
	CheckCloudAWSS3NoEncryption:    {"SOC2-CC6.1", "PCI-3.5", "HIPAA-164.312(a)(2)", "NIST-PR.DS"},
	CheckCloudAWSEC2PublicSG:       {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},
	CheckCloudAWSEKSPublicEndpoint: {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},

	// ── Cloud — Azure ───────────────────────────────────────────────────────
	CheckCloudAzureBlobPublic:        {"SOC2-CC6.6", "PCI-1.3", "HIPAA-164.312(a)(1)", "NIST-PR.DS"},
	CheckCloudAzureStorageHTTP:       {"SOC2-CC6.7", "PCI-4.2.1", "HIPAA-164.312(e)(2)", "NIST-PR.DS"},
	CheckCloudAzureAKSPublicEndpoint: {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},
	CheckCloudAzureOwnerDirect:       {"SOC2-CC6.3", "PCI-7.2", "NIST-PR.AC", "ISO27001-A.9.2"},

	// ── WHOIS ───────────────────────────────────────────────────────────────
	CheckWHOISDomainExpiry7d:  {"SOC2-CC9.1"},
	CheckWHOISDomainExpiry30d: {"SOC2-CC9.1"},

	// ── CMS ─────────────────────────────────────────────────────────────────
	CheckCMSPluginVulnerable: {"PCI-6.3.3", "SOC2-CC6.6"},

	// ── CVEs — all KEV/critical vulnerabilities ─────────────────────────────
	// Pattern: unpatched CVE → PCI-6.3.3 (patch management) + SOC2-CC6.6 (vuln mgmt)
	// RCE CVEs also get NIST-PR.IP (information protection)
	CheckCVELog4Shell:                {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEN8nRCE:                   {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVECraftCMSRCE:              {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVELivewireRCE:              {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEBeyondTrustRCE:           {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVENginxUIBackup:            {"PCI-6.3.3", "SOC2-CC6.6"},
	CheckCVESolarWindsWHD:            {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEIvantiEPMAuthBypass:      {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVELangflowRCE:              {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEOmnissaSSRF:              {"PCI-6.3.3", "SOC2-CC6.6"},
	CheckCVEKeycloakSAMLBypass:       {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.AC"},
	CheckCVEStruts2S2066:             {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVERailsXMLRCE:              {"PCI-6.3.3", "SOC2-CC6.6"},
	CheckCVEHFSRejetto:               {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEManageEngineServiceDesk:  {"PCI-6.3.3", "SOC2-CC6.6"},
	CheckCVEMinIOEnvDisclosure:       {"SOC2-CC6.1", "PCI-6.3.1", "HIPAA-164.312(a)(1)"},
	CheckCVEOllamaPathTraversal:      {"PCI-6.3.3", "SOC2-CC6.6"},
	CheckCVEFortiOSWSAuthBypass:      {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEIvantiCS2025:             {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVESAPNetWeaver2025:         {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEIvantiEPMMRCE:            {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVECiscoFMCRCE:              {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEHPEOneViewRCE:            {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVECitrixBleed2:             {"PCI-6.3.3", "SOC2-CC6.6"},
	CheckCVEFortiOSSSOBypass:         {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.AC"},
	CheckCVEFortiWebAuthBypass:       {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVECiscoASARCE:              {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEMCPServerExposed:         {"PCI-6.3.3", "SOC2-CC6.6"},
	CheckCVEErlangOTPSSH:             {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEVeeamBackupExposed:       {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVESupersetDefaultKey:       {"PCI-6.3.3", "SOC2-CC6.6"},
	CheckCVEMLflowAuthBypass:         {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.AC"},
	CheckCVEHarborDefaultCreds:       {"PCI-6.3.3", "SOC2-CC6.2", "NIST-PR.AC"},
	CheckCVEGrafanaPathTraversal:     {"PCI-6.3.3", "SOC2-CC6.6"},
	CheckCVEZabbixSessionForge:       {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.AC"},
	CheckCVEpgAdminValidateRCE:       {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEGiteaCMDInjection:        {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEAirflowDAGRCE:            {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVELibupnpSSDPRCE:           {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckPortJuniperAnomalyExposed:   {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckPortTelnetdVulnerable:       {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVETelnetBSDEncrypt:         {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckPortFTPWingRCE:              {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckPortRedisVulnerableCVE2025:  {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckPortKibanaVulnerable:        {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVENextJSMiddlewareBypass:   {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.AC"},
	CheckCVEViteFileRead:             {"PCI-6.3.3", "SOC2-CC6.6"},
	CheckCVEIngressNightmare:         {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVETomcatPartialPUT:         {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEOpenSSHRegreSSHion:       {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEJenkinsCLIFileRead:       {"PCI-6.3.3", "SOC2-CC6.6"},
	CheckCVEScreenConnectBypass:      {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVETeamCityAuthBypass:       {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.AC"},
	CheckCVEFortiManagerJump:         {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEPHPCGIArgInjection:       {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEExpeditionRCE:            {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEFortiOSSSLVPN:            {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVECheckPointFileRead:       {"PCI-6.3.3", "SOC2-CC6.6"},
	CheckCVESharePointJWT:            {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.AC"},
	CheckCVEOwnCloudPhpInfo:          {"PCI-6.3.3", "SOC2-CC6.6"},
	CheckCVEMOVEitWebShell:           {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEConfluenceSetup:          {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEConfluenceRestore:        {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVECiscoIOSXEImplant:        {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEIvantiConnectSecure:      {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.AC"},
	CheckCVEIvantiCMDInjection:       {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVECitrixBleed:              {"PCI-6.3.3", "SOC2-CC6.6"},
	CheckCVECitrixADCRCE2023:         {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEJuniperJWeb:              {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEJuniperJWeb2024:          {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVESysAid:                   {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVETeamCityRPC2:             {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.AC"},
	CheckCVETeamCityDirTraversal:     {"PCI-6.3.3", "SOC2-CC6.6"},
	CheckCVEBarracudaESG:             {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEOpenfire:                 {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.AC"},
	CheckCVECiscoASASSLVPN:           {"PCI-6.3.3", "SOC2-CC6.6"},
	CheckCVERoundcube:                {"PCI-6.3.3", "SOC2-CC6.6"},
	CheckCVEF5BigIPAuthBypass:        {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEConfluenceOGNL:           {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEFortiOSAuthBypass:        {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.AC"},
	CheckCVEVMwareWorkspaceONE:       {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEWSO2FileUpload:           {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVESpring4Shell:             {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEZimbraAuthBypass:         {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.AC"},
	CheckCVESophosFW:                 {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEManageEngineSAML:         {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEMagentoRCE:               {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEOracleEBS:                {"PCI-6.3.3", "SOC2-CC6.6"},
	CheckCVEExchangeProxyLogon:       {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEExchangeProxyShell:       {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEvCenterExposed:           {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEApacheHTTPTraversal:      {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEGitLabRCE:                {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVESaltStackAPI:             {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEAccellionFTA:             {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEManageEngineADSelfSvc:    {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVESonicWallSMAExposed:      {"PCI-6.3.3", "SOC2-CC6.6"},
	CheckCVEF5BigIPTMUI:              {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEWebLogicConsole:          {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVECitrixADCInfo:            {"PCI-6.3.3", "SOC2-CC6.6"},
	CheckCVESolarWindsOrion:          {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEApacheUnomi:              {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVELiferayRCE:               {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEMobileIronRCE:            {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEvBulletin5xRCE:           {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEPulseSecureVPN:           {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEPANGlobalProtect:         {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEPANGlobalProtectCMD:      {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVECrowdPdkInstall:          {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.AC"},
	CheckCVETelerikRAU:               {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEWebLogicAsync:            {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVESolrAdminExposed:         {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEEximRCE2019:              {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEDLinkHNAP:                {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEDrupalgeddon2:            {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEManageEngineDesktopCVE:   {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEKubernetesPrivEsc:        {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.AC"},
	CheckCVEJenkinsStaplerRCE:        {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEEximHeapOverflow:         {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEApacheTikaRCE:            {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEFortiOSCredLeak:          {"PCI-6.3.3", "SOC2-CC6.6"},
	CheckCVEColdFusionFCKEditor:      {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEStruts2OGNL:              {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEWebLogicWLSWSAT:          {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVEHikvisionISAPI:           {"PCI-6.3.3", "SOC2-CC6.6"},
	CheckCVEOpenSSHUsernameEnum:      {"PCI-6.3.3", "SOC2-CC6.6"},
}
