package finding

// ComplianceTags returns the compliance framework control IDs that a given
// CheckID maps to. Returns nil if the check has no specific compliance mapping.
//
// Frameworks mapped:
//   - SOC2 Trust Service Criteria (CC6.x, CC7.x, CC8.x, CC9.x)
//   - PCI DSS v4.0 (1.x–12.x)
//   - NIST CSF (PR.AC, PR.DS, PR.IP, PR.PT, DE.AE)
//   - HIPAA Security Rule (164.3xx)
//   - ISO 27001:2022 Annex A (A.x.x)
//   - CIS Controls v8 (CIS-X.Y)
func ComplianceTags(id CheckID) []string {
	if tags, ok := complianceMap[id]; ok {
		return tags
	}
	return nil
}

var complianceMap = map[CheckID][]string{

	// ── Email Security ──────────────────────────────────────────────────────
	CheckEmailSPFMissing:            {"SOC2-CC6.1", "NIST-PR.IP", "CIS-9.2"},
	CheckEmailSPFSoftfail:           {"SOC2-CC6.1", "CIS-9.2"},
	CheckEmailSPFLookupLimit:        {"SOC2-CC6.1", "CIS-9.2"},
	CheckEmailDMARCMissing:          {"SOC2-CC6.1", "NIST-PR.IP", "ISO27001-A.13.2", "CIS-9.2"},
	CheckEmailDMARCPolicyNone:       {"SOC2-CC6.1", "ISO27001-A.13.2", "CIS-9.2"},
	CheckEmailDMARCSubdomainNone:    {"SOC2-CC6.1", "ISO27001-A.13.2", "CIS-9.2"},
	CheckEmailDMARCNoReporting:      {"SOC2-CC6.1", "CIS-9.2"},
	CheckEmailDKIMMissing:           {"SOC2-CC6.1", "NIST-PR.IP", "CIS-9.2"},
	CheckEmailDKIMWeakKey:           {"SOC2-CC6.7", "NIST-PR.IP", "CIS-9.2"},
	CheckEmailMTASTSMissing:         {"SOC2-CC6.7", "NIST-PR.DS", "CIS-9.2"},
	CheckEmailMTASTSNotEnforced:     {"SOC2-CC6.7", "CIS-9.2"},
	CheckEmailMTASTSPolicyFetchFail: {"SOC2-CC6.7", "CIS-9.2"},
	CheckEmailTLSRPTMissing:         {"SOC2-CC6.7", "CIS-9.2"},
	CheckEmailDANEMissing:           {"SOC2-CC6.7", "CIS-9.2"},
	CheckEmailSpoofable:             {"SOC2-CC6.1", "PCI-12.10", "HIPAA-164.308(a)(5)", "CIS-9.2"},
	CheckEmailSMTPOpenRelay:         {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC", "CIS-9.2"},
	CheckEmailSMTPBannerLeak:        {"SOC2-CC6.6", "CIS-9.2"},

	// ── TLS / SSL ───────────────────────────────────────────────────────────
	CheckTLSCertExpiry7d:          {"SOC2-CC9.1", "PCI-4.2.1", "CIS-3.10"},
	CheckTLSCertExpiry30d:         {"SOC2-CC9.1", "PCI-4.2.1", "CIS-3.10"},
	CheckTLSCertSelfSigned:        {"SOC2-CC6.7", "PCI-4.2.1", "HIPAA-164.312(e)(2)", "CIS-3.10"},
	CheckTLSCertHostnameMismatch:  {"SOC2-CC6.7", "PCI-4.2.1", "CIS-3.10"},
	CheckTLSCertChainInvalid:      {"SOC2-CC6.7", "PCI-4.2.1", "CIS-3.10"},
	CheckTLSProtocolSSLv2:         {"PCI-4.2.1", "SOC2-CC6.7", "HIPAA-164.312(e)(2)", "CIS-3.10"},
	CheckTLSProtocolSSLv3:         {"PCI-4.2.1", "SOC2-CC6.7", "HIPAA-164.312(e)(2)", "CIS-3.10"},
	CheckTLSProtocolTLS10:         {"PCI-4.2.1", "SOC2-CC6.7", "CIS-3.10"},
	CheckTLSProtocolTLS11:         {"PCI-4.2.1", "SOC2-CC6.7", "CIS-3.10"},
	CheckTLSWeakCipher:            {"PCI-4.2.1", "SOC2-CC6.7", "HIPAA-164.312(e)(2)", "CIS-3.10"},
	CheckTLSBEAST:                 {"PCI-4.2.1", "SOC2-CC6.7", "CIS-3.10"},
	CheckTLSHeartbleed:            {"PCI-6.3.3", "SOC2-CC6.6", "CIS-7.4"},
	CheckTLSPOODLE:                {"PCI-6.3.3", "SOC2-CC6.7", "CIS-3.10"},
	CheckTLSROBOT:                 {"PCI-6.3.3", "CIS-3.10"},
	CheckTLSCCSInjection:          {"PCI-6.3.3", "SOC2-CC6.6", "CIS-7.4"},
	CheckTLSCertWeakKey:           {"SOC2-CC6.7", "PCI-4.2.1", "NIST-PR.DS", "CIS-3.10"},
	CheckTLSCertWeakSignature:     {"SOC2-CC6.7", "PCI-4.2.1", "CIS-3.10"},
	CheckTLSCertRevoked:           {"SOC2-CC6.7", "PCI-4.2.1", "CIS-3.10"},
	CheckTLSNoPFS:                 {"SOC2-CC6.7", "PCI-4.2.1", "NIST-PR.DS", "CIS-3.10"},
	CheckTLSMixedContent:          {"SOC2-CC6.7", "PCI-4.2.1", "CIS-3.10"},
	CheckTLSNoSecureRenegotiation: {"SOC2-CC6.7", "PCI-4.2.1", "CIS-3.10"},
	CheckTLSCertSANMissing:        {"SOC2-CC6.7", "CIS-3.10"},
	CheckTLSHSTSShortMaxAge:       {"SOC2-CC6.7", "CIS-9.4"},

	// ── DNS Security ────────────────────────────────────────────────────────
	CheckDNSAXFRAllowed:   {"SOC2-CC6.1", "ISO27001-A.12.4", "CIS-12.1"},
	CheckDNSWildcard:      {"SOC2-CC6.6", "CIS-12.1"},
	CheckDNSDanglingCNAME: {"SOC2-CC6.6", "NIST-PR.IP", "CIS-12.1"},
	CheckDNSMissingCAA:    {"SOC2-CC6.7", "CIS-12.1"},
	CheckDNSDNSSECMissing: {"SOC2-CC6.7", "NIST-PR.DS", "CIS-12.1"},

	// ── HTTP Security Headers ───────────────────────────────────────────────
	CheckHeadersMissingCSP:               {"SOC2-CC6.6", "PCI-6.4.1", "NIST-PR.IP", "CIS-9.4"},
	CheckHeadersMissingHSTS:              {"SOC2-CC6.7", "PCI-4.2.1", "NIST-PR.DS", "CIS-9.4"},
	CheckHeadersMissingXFrameOptions:     {"SOC2-CC6.6", "PCI-6.4.1", "CIS-9.4"},
	CheckHeadersMissingXContentType:      {"SOC2-CC6.6", "PCI-6.4.1", "CIS-9.4"},
	CheckHeadersMissingReferrerPolicy:    {"SOC2-CC6.6", "CIS-9.4"},
	CheckHeadersMissingPermissionsPolicy: {"SOC2-CC6.6", "CIS-9.4"},
	CheckHeadersServerInfoLeak:           {"SOC2-CC6.6", "PCI-6.4", "CIS-4.8"},

	// ── Exposure / Misconfiguration ─────────────────────────────────────────
	CheckExposureHTTPNoRedirect:   {"SOC2-CC6.7", "PCI-4.2.1", "CIS-3.10"},
	CheckExposureStagingSubdomain: {"SOC2-CC6.6", "PCI-6.4", "CIS-4.8"},
	CheckExposureAdminPath:        {"SOC2-CC6.6", "PCI-6.4", "CIS-4.8"},
	CheckExposureRobotsLeak:       {"SOC2-CC6.6", "CIS-4.8"},
	CheckExposureEnvFile:          {"SOC2-CC6.1", "PCI-6.3.1", "HIPAA-164.312(a)(1)", "CIS-3.7"},
	CheckExposureGitExposed:       {"SOC2-CC6.1", "PCI-6.3.1", "CIS-3.7"},
	CheckExposureBackupFile:       {"SOC2-CC6.1", "PCI-6.3.1", "CIS-3.7"},
	CheckExposureAPIDocs:          {"SOC2-CC6.6", "CIS-4.8"},
	CheckExposureMonitoringPanel:  {"SOC2-CC6.6", "CIS-4.8"},
	CheckExposureCICDPanel:        {"SOC2-CC8.1", "PCI-6.3", "CIS-16.5"},
	CheckExposureSpringActuator:   {"SOC2-CC6.6", "PCI-6.4", "CIS-4.8"},
	CheckExposureCloudStorage:     {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.DS", "CIS-3.7"},
	CheckExposureSensitiveFile:    {"SOC2-CC6.1", "PCI-6.3.1", "CIS-3.7"},
	CheckExposureAIModelFile:     {"SOC2-CC6.1", "PCI-6.3.1", "CIS-3.7"},

	// ── Subdomain / Domain ──────────────────────────────────────────────────
	CheckSubdomainTakeover: {"SOC2-CC6.6", "NIST-PR.IP", "CIS-12.1"},
	CheckDomainTyposquat:   {"SOC2-CC6.6", "CIS-12.1"},

	// ── Web Application Security ────────────────────────────────────────────
	CheckWebXSS:                    {"PCI-6.4.1", "SOC2-CC6.6", "CIS-16.2"},
	CheckWebSQLi:                   {"PCI-6.4.1", "SOC2-CC6.6", "HIPAA-164.312(a)(1)", "CIS-16.2"},
	CheckWebOpenRedirect:           {"SOC2-CC6.6", "PCI-6.4.1", "CIS-16.2"},
	CheckWebSSRF:                   {"PCI-6.4.1", "SOC2-CC6.6", "NIST-PR.AC", "CIS-16.2"},
	CheckWebPathTraversal:          {"PCI-6.4.1", "SOC2-CC6.6", "HIPAA-164.312(a)(1)", "CIS-16.2"},
	CheckWebDefaultCredentials:     {"PCI-8.3.9", "SOC2-CC6.2", "CIS-5.2"},
	CheckWebHTTPRequestSmuggling:   {"PCI-6.4.1", "SOC2-CC6.6", "CIS-16.2"},
	CheckWebDangerousMethodEnabled: {"SOC2-CC6.6", "PCI-6.4", "CIS-4.8"},
	CheckSecretInResponseHeader:    {"SOC2-CC6.1", "PCI-6.3.1", "CIS-3.7"},
	CheckWebDebugEndpoint:          {"SOC2-CC6.6", "PCI-6.4", "CIS-4.8"},
	CheckWebErrorInfoLeak:          {"SOC2-CC6.6", "PCI-6.4", "CIS-4.8"},
	CheckWebSSTI:                   {"PCI-6.4.1", "SOC2-CC6.6", "CIS-16.2"},
	CheckWebCRLFInjection:          {"PCI-6.4.1", "SOC2-CC6.6", "CIS-16.2"},
	CheckWebPrototypePollution:     {"PCI-6.4.1", "SOC2-CC6.6", "CIS-16.2"},
	CheckWebXXE:                    {"PCI-6.4.1", "SOC2-CC6.6", "CIS-16.2"},
	CheckWebInsecureDeserialize:    {"PCI-6.4.1", "SOC2-CC6.6", "CIS-16.2"},
	CheckWebDotNetDeserialize:      {"PCI-6.4.1", "SOC2-CC6.6", "CIS-16.2"},
	CheckWebCmdInjection:           {"PCI-6.4.1", "SOC2-CC6.6", "HIPAA-164.312(a)(1)", "NIST-PR.IP", "CIS-16.2"},
	CheckWebCSRFMissing:            {"PCI-6.4.1", "SOC2-CC6.6", "CIS-16.2"},
	CheckWebSSRFRedirectMetadata:   {"PCI-6.4.1", "SOC2-CC6.6", "NIST-PR.AC", "CIS-16.2"},
	CheckWebHPP:                    {"PCI-6.4.1", "SOC2-CC6.6", "CIS-16.2"},
	CheckWebNginxAliasTraversal:    {"PCI-6.4.1", "SOC2-CC6.6", "CIS-16.2"},
	CheckWebIISShortname:           {"SOC2-CC6.6", "CIS-4.8"},
	CheckWebFileUpload:             {"PCI-6.4.1", "SOC2-CC6.6", "CIS-16.2"},
	CheckHTTPClickjacking:          {"PCI-6.4.1", "SOC2-CC6.6", "CIS-9.4"},
	CheckWebSocketCSWSH:            {"PCI-6.4.1", "SOC2-CC6.6", "CIS-16.2"},
	CheckHostHeaderInjection:       {"PCI-6.4.1", "SOC2-CC6.6", "CIS-16.2"},
	CheckSwaggerExposed:            {"SOC2-CC6.6", "CIS-4.8"},

	// ── CORS ────────────────────────────────────────────────────────────────
	CheckCORSMisconfiguration:       {"PCI-6.4.1", "SOC2-CC6.6", "CIS-16.2"},
	CheckCORSNullOrigin:             {"PCI-6.4.1", "SOC2-CC6.6", "CIS-16.2"},
	CheckCORSPreflightMisconfig:     {"PCI-6.4.1", "SOC2-CC6.6", "CIS-16.2"},
	CheckCORSCredentialedReflection: {"PCI-6.4.1", "SOC2-CC6.6", "NIST-PR.AC", "CIS-16.2"},

	// ── Cookies ─────────────────────────────────────────────────────────────
	CheckCookieMissingSecure:   {"SOC2-CC6.7", "PCI-4.2.1", "CIS-16.2"},
	CheckCookieMissingHTTPOnly: {"SOC2-CC6.6", "PCI-6.4.1", "CIS-16.2"},
	CheckCookieMissingSameSite: {"SOC2-CC6.6", "PCI-6.4.1", "CIS-16.2"},

	// ── CSP ─────────────────────────────────────────────────────────────────
	CheckCSPUnsafeInline:   {"SOC2-CC6.6", "PCI-6.4.1", "CIS-9.4"},
	CheckCSPUnsafeEval:     {"SOC2-CC6.6", "PCI-6.4.1", "CIS-9.4"},
	CheckCSPWildcardSource: {"SOC2-CC6.6", "PCI-6.4.1", "CIS-9.4"},

	// ── WAF ─────────────────────────────────────────────────────────────────
	CheckWAFOriginExposed:  {"SOC2-CC6.6", "PCI-1.3", "CIS-13.6"},
	CheckWAFBypassHeader:   {"SOC2-CC6.6", "PCI-1.3", "CIS-13.6"},
	CheckWAFInsecureMode:   {"SOC2-CC6.7", "PCI-4.2.1", "CIS-13.6"},

	// ── DLP ─────────────────────────────────────────────────────────────────
	CheckDLPSSN:           {"HIPAA-164.312", "PCI-3.4", "SOC2-CC6.1", "CIS-3.7"},
	CheckDLPCreditCard:    {"PCI-3.4", "PCI-3.5", "SOC2-CC6.1", "CIS-3.7"},
	CheckDLPDatabaseURL:   {"SOC2-CC6.1", "PCI-6.3.1", "CIS-3.7"},
	CheckDLPPrivateKey:    {"SOC2-CC6.1", "PCI-6.3.1", "CIS-3.7"},
	CheckDLPAPIKey:        {"SOC2-CC6.1", "PCI-6.3.1", "CIS-3.7"},
	CheckDLPEmailList:     {"HIPAA-164.312", "SOC2-CC6.1", "CIS-3.7"},
	CheckDLPVision:        {"PCI-3.4", "HIPAA-164.312", "CIS-3.7"},
	CheckVisionServiceID:  {"SOC2-CC6.6", "CIS-4.8"},
	CheckDLPWifiCredential: {"SOC2-CC6.1", "PCI-6.3.1", "CIS-3.7"},

	// ── JS Content Analysis ─────────────────────────────────────────────────
	CheckJSHardcodedSecret:  {"SOC2-CC6.1", "PCI-6.3.1", "CIS-3.7"},
	CheckJSInternalEndpoint: {"SOC2-CC6.6", "CIS-4.8"},
	CheckJSSourceMapExposed: {"SOC2-CC6.6", "PCI-6.3.1", "CIS-3.7"},

	// ── Cloud Storage Buckets ───────────────────────────────────────────────
	CheckCloudBucketPublic:   {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.DS", "CIS-3.3"},
	CheckCloudBucketWritable: {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.DS", "CIS-3.3"},
	CheckNucleiS3BucketExposed:   {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.DS", "CIS-3.3"},
	CheckNucleiMisconfiguredCORS: {"PCI-6.4.1", "SOC2-CC6.6", "CIS-16.2"},

	// ── Port / Service Exposure ─────────────────────────────────────────────
	CheckPortRedisUnauth:           {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC", "CIS-4.4"},
	CheckPortElasticsearchUnauth:   {"SOC2-CC6.6", "PCI-1.3", "HIPAA-164.312", "CIS-4.4"},
	CheckPortPrometheusUnauth:      {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortDockerUnauth:          {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC", "CIS-4.4"},
	CheckPortKubeletUnauth:         {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC", "CIS-4.4"},
	CheckPortMemcachedUnauth:       {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortJupyterExposed:        {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortCouchDBUnauth:         {"SOC2-CC6.6", "PCI-1.3", "HIPAA-164.312", "CIS-4.4"},
	CheckPortSSHExposed:            {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortRDPExposed:            {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC", "CIS-4.4"},
	CheckPortVNCExposed:            {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC", "CIS-4.4"},
	CheckPortTelnetExposed:         {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC", "CIS-4.4"},
	CheckPortFTPExposed:            {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortFTPAnonymous:          {"SOC2-CC6.2", "PCI-1.3", "NIST-PR.AC", "CIS-5.2"},
	CheckPortFTPVsftpdBackdoor:     {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckPortSMBExposed:            {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortSMBNullSession:        {"SOC2-CC6.2", "PCI-1.3", "NIST-PR.AC", "CIS-5.2"},
	CheckPortSMBv1Enabled:          {"SOC2-CC6.6", "PCI-1.3", "PCI-6.3.3", "CIS-4.8"},
	CheckPortDatabaseExposed:       {"SOC2-CC6.6", "PCI-1.3", "HIPAA-164.312", "CIS-4.4"},
	CheckPortK8sAPIExposed:         {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC", "CIS-4.4"},
	CheckPortWinRMExposed:          {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC", "CIS-4.4"},
	CheckPortAMQPExposed:           {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortKafkaExposed:          {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortZooKeeperExposed:      {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortInfluxDBExposed:       {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortSplunkMgmtExposed:     {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortCiscoSmartInstall:     {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC", "CIS-4.4"},
	CheckPortHuggingFaceTGIExposed: {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortAutomatic1111Exposed:  {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortNacosExposed:          {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC", "CIS-4.4"},
	CheckPortConsulNoACL:           {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC", "CIS-4.4"},
	CheckPortNiFiExposed:           {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortOllamaExposed:         {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortRabbitMQMgmtExposed:   {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortTektonDashboardExposed: {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortHarborExposed:          {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC", "CIS-4.4"},
	CheckPortArgoCDExposed:          {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortAirflowExposed:         {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortOpenWebUIExposed:       {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortPulsarAdminExposed:     {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortSGLangExposed:          {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortAdGuardExposed:         {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortStepCAExposed:          {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC", "CIS-4.4"},
	CheckPortArtifactoryExposed:     {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC", "CIS-4.4"},
	CheckPortNexusExposed:           {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC", "CIS-4.4"},
	CheckPortGRPCReflectionEnabled:  {"SOC2-CC6.6", "NIST-PR.IP", "CIS-4.8"},
	CheckPortDevServerExposed:       {"SOC2-CC6.6", "PCI-6.4", "CIS-4.8"},
	CheckPortGradioExposed:          {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortWebminExposed:          {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortWazuhAPIExposed:        {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortSupersetExposed:        {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortMLflowExposed:          {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortRayDashboardExposed:    {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortNATSMonitoringExposed:  {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortClickHouseExposed:      {"SOC2-CC6.6", "PCI-1.3", "HIPAA-164.312", "CIS-4.4"},
	CheckPortBGPExposed:             {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortMinIODefaultCreds:      {"SOC2-CC6.2", "PCI-8.3.9", "NIST-PR.AC", "CIS-5.2"},

	// ── Port — default credentials ──────────────────────────────────────────
	CheckPortRabbitMQDefaultCreds: {"SOC2-CC6.2", "PCI-8.3.9", "NIST-PR.AC", "CIS-5.2"},
	CheckPortMySQLNoAuth:          {"SOC2-CC6.2", "PCI-8.3.9", "HIPAA-164.312(a)(1)", "NIST-PR.AC", "CIS-5.2"},
	CheckPortPostgreSQLTrust:      {"SOC2-CC6.2", "PCI-8.3.9", "HIPAA-164.312(a)(1)", "NIST-PR.AC", "CIS-5.2"},
	CheckPortMSSQLDefaultCreds:    {"SOC2-CC6.2", "PCI-8.3.9", "HIPAA-164.312(a)(1)", "NIST-PR.AC", "CIS-5.2"},

	// ── Email / messaging port exposure ─────────────────────────────────────
	CheckPortSMTPExposed:       {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortIMAPExposed:       {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortPOP3Exposed:       {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortSMTPOpenRelay:     {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC", "CIS-4.4"},
	CheckPortExImVulnerable:    {"PCI-6.3.3", "SOC2-CC6.6", "CIS-7.4"},

	// ── Directory services ──────────────────────────────────────────────────
	CheckPortLDAPExposed:            {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC", "CIS-4.4"},
	CheckPortActiveDirectoryExposed: {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC", "CIS-4.4"},
	CheckPortKerberosExposed:        {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC", "CIS-4.4"},
	CheckPortGlobalCatalogExposed:   {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC", "CIS-4.4"},

	// ── NFS / RPC / SNMP ────────────────────────────────────────────────────
	CheckPortRPCBindExposed:         {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortNFSExportsExposed:      {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC", "CIS-4.4"},
	CheckPortSNMPPublicCommunity:    {"SOC2-CC6.2", "PCI-1.3", "NIST-PR.AC", "CIS-4.4"},
	CheckPortSNMPWritableCommunity:  {"SOC2-CC6.2", "PCI-1.3", "NIST-PR.AC", "CIS-4.4"},
	CheckPortEPMDExposed:            {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortWINSExposed:            {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},

	// ── UDP service exposure ────────────────────────────────────────────────
	CheckPortNTPAmplification:   {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortTFTPAnonymous:      {"SOC2-CC6.2", "PCI-1.3", "NIST-PR.AC", "CIS-4.4"},
	CheckPortSSDPExposed:        {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortIKEExposed:         {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortNetBIOSNSExposed:   {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortMDNSExposed:        {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortDNSOpenResolver:    {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},

	// ── ICS / SCADA / OT ────────────────────────────────────────────────────
	CheckPortModbusExposed:     {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC", "CIS-4.4"},
	CheckPortS7CommExposed:     {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC", "CIS-4.4"},
	CheckPortEtherNetIPExposed: {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC", "CIS-4.4"},
	CheckPortDNP3Exposed:       {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC", "CIS-4.4"},
	CheckPortBACnetExposed:     {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortMQTTExposed:       {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC", "CIS-4.4"},
	CheckPortSIPExposed:        {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortRTSPExposed:       {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortIPPExposed:        {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortISCSIExposed:      {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.DS", "CIS-4.4"},
	CheckPortNetconfExposed:    {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortWinboxExposed:     {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortJetDirectExposed:  {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortMikroTikAPIExposed: {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortCheckPointExposed:  {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortNeo4jExposed:       {"SOC2-CC6.6", "PCI-1.3", "HIPAA-164.312", "CIS-4.4"},
	CheckPortAsteriskAMIExposed: {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},

	// ── GraphQL ─────────────────────────────────────────────────────────────
	CheckGraphQLIntrospection:        {"SOC2-CC6.6", "NIST-PR.IP", "CIS-4.8"},
	CheckGraphQLBatchQuery:           {"SOC2-CC6.6", "CIS-16.2"},
	CheckGraphQLPersistedQueryBypass: {"SOC2-CC6.6", "CIS-16.2"},
	CheckGraphQLGETEnabled:           {"SOC2-CC6.6", "PCI-6.4.1", "CIS-16.2"},
	CheckGraphQLAliasDos:             {"SOC2-CC6.6", "CIS-16.2"},

	// ── JWT ─────────────────────────────────────────────────────────────────
	CheckJWTWeakAlg:            {"SOC2-CC6.7", "PCI-4.2.1", "NIST-PR.DS", "CIS-3.10"},
	CheckJWTLongExpiry:         {"SOC2-CC6.1", "NIST-PR.AC", "CIS-5.2"},
	CheckJWTSensitivePayload:   {"SOC2-CC6.1", "PCI-3.4", "HIPAA-164.312", "CIS-3.7"},
	CheckJWTAlgNoneVariant:     {"SOC2-CC6.7", "PCI-4.2.1", "NIST-PR.DS", "CIS-3.10"},
	CheckJWTEmptySecret:        {"SOC2-CC6.7", "PCI-4.2.1", "CIS-3.10"},
	CheckJWTKidInjection:       {"PCI-6.4.1", "SOC2-CC6.6", "CIS-16.2"},
	CheckJWTNoVerification:     {"SOC2-CC6.7", "PCI-8.3.1", "NIST-PR.AC", "CIS-5.2"},
	CheckJWTAlgorithmConfusion: {"SOC2-CC6.7", "PCI-4.2.1", "NIST-PR.DS", "CIS-3.10"},
	CheckJWTAudienceMissing:    {"SOC2-CC6.1", "NIST-PR.AC", "CIS-5.2"},
	CheckJWTIssuerNotValidated: {"SOC2-CC6.1", "NIST-PR.AC", "CIS-5.2"},
	CheckJWTEncryptionMissing:  {"SOC2-CC6.7", "PCI-3.4", "CIS-3.10"},
	CheckJWTReplayMissing:      {"SOC2-CC6.6", "NIST-PR.AC", "CIS-5.2"},
	CheckJWKSWeakKey:           {"SOC2-CC6.7", "PCI-4.2.1", "CIS-3.10"},
	CheckJWKSMissingKID:        {"SOC2-CC6.7", "CIS-3.10"},

	// ── OAuth / OIDC ────────────────────────────────────────────────────────
	CheckOAuthMissingState:      {"SOC2-CC6.6", "PCI-6.4.1", "NIST-PR.AC", "CIS-16.2"},
	CheckOAuthWeakState:         {"SOC2-CC6.6", "PCI-6.4.1", "CIS-16.2"},
	CheckOAuthMissingPKCE:       {"SOC2-CC6.6", "NIST-PR.AC", "CIS-16.2"},
	CheckOAuthOpenRedirect:      {"SOC2-CC6.6", "PCI-6.4.1", "CIS-16.2"},
	CheckOAuthSubdomainBypass:   {"SOC2-CC6.6", "PCI-6.4.1", "CIS-16.2"},
	CheckOAuthTokenLeakReferer:  {"SOC2-CC6.1", "PCI-6.3.1", "CIS-3.7"},
	CheckOIDCImplicitFlow:       {"SOC2-CC6.6", "NIST-PR.AC", "CIS-16.2"},
	CheckOAuthImplicitAccepted:  {"SOC2-CC6.6", "NIST-PR.AC", "CIS-16.2"},
	CheckOIDCWeakSigningAlg:     {"SOC2-CC6.7", "PCI-4.2.1", "CIS-3.10"},
	CheckOIDCMissingJWKSURI:     {"SOC2-CC6.7", "CIS-3.10"},
	CheckOAuthTokenInFragment:   {"SOC2-CC6.1", "PCI-6.3.1", "CIS-3.7"},
	CheckOAuthRefreshNotRotated: {"SOC2-CC6.1", "NIST-PR.AC", "CIS-5.2"},
	CheckOAuthTokenLongExpiry:   {"SOC2-CC6.1", "NIST-PR.AC", "CIS-5.2"},
	CheckOIDCBackchannelMissing: {"SOC2-CC6.6", "CIS-16.2"},

	// ── SAML ────────────────────────────────────────────────────────────────
	CheckSAMLEndpointExposed:       {"SOC2-CC6.6", "CIS-4.8"},
	CheckSAMLMetadataExposed:       {"SOC2-CC6.6", "CIS-4.8"},
	CheckSAMLSignatureNotValidated: {"SOC2-CC6.7", "PCI-8.3.1", "NIST-PR.AC", "CIS-5.2"},
	CheckSAMLXMLWrapping:           {"SOC2-CC6.7", "PCI-6.4.1", "CIS-16.2"},
	CheckSAMLReplayAllowed:         {"SOC2-CC6.6", "NIST-PR.AC", "CIS-5.2"},
	CheckSAMLIssuerNotValidated:    {"SOC2-CC6.1", "NIST-PR.AC", "CIS-5.2"},
	CheckSAMLAudienceNotValidated:  {"SOC2-CC6.1", "NIST-PR.AC", "CIS-5.2"},
	CheckSAMLXXEInjection:          {"PCI-6.4.1", "SOC2-CC6.6", "CIS-16.2"},
	CheckSAMLOpenRedirect:          {"SOC2-CC6.6", "PCI-6.4.1", "CIS-16.2"},

	// ── IAM / Identity Management ───────────────────────────────────────────
	CheckSCIMExposed:             {"SOC2-CC6.6", "NIST-PR.AC", "CIS-4.8"},
	CheckSCIMUnauthenticated:     {"SOC2-CC6.2", "PCI-8.3.1", "NIST-PR.AC", "CIS-5.2"},
	CheckOIDCUserinfoLeak:        {"SOC2-CC6.1", "HIPAA-164.312", "CIS-3.7"},
	CheckOAuthIntrospectExposed:  {"SOC2-CC6.6", "NIST-PR.AC", "CIS-4.8"},
	CheckOAuthDeviceFlowExposed:  {"SOC2-CC6.6", "CIS-4.8"},
	CheckOAuthDynClientReg:       {"SOC2-CC6.6", "NIST-PR.AC", "CIS-4.8"},
	CheckLDAPInjection:           {"PCI-6.4.1", "SOC2-CC6.6", "NIST-PR.AC", "CIS-16.2"},
	CheckCloudMetadataSSRF:       {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC", "CIS-16.2"},
	CheckIdentityProviderExposed: {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC", "CIS-4.8"},
	CheckOAuthPKCEDowngrade:      {"SOC2-CC6.6", "NIST-PR.AC", "CIS-16.2"},
	CheckOAuthClientSecretLeak:   {"SOC2-CC6.1", "PCI-6.3.1", "CIS-3.7"},
	CheckIdentityRoleEscalation:  {"SOC2-CC6.3", "PCI-7.2", "NIST-PR.AC", "CIS-6.8"},

	// ── API Security ────────────────────────────────────────────────────────
	CheckRateLimitMissing:      {"SOC2-CC6.6", "CIS-13.6"},
	CheckRateLimitBypass:       {"SOC2-CC6.6", "CIS-13.6"},

	// ── Dirbusting ──────────────────────────────────────────────────────────
	CheckDirbustFound: {"SOC2-CC6.6", "CIS-4.8"},

	// ── GitHub Actions ──────────────────────────────────────────────────────
	CheckGHActionUnpinned:                    {"SOC2-CC8.1", "PCI-6.3", "NIST-PR.IP", "CIS-16.5"},
	CheckGHActionPRTargetUnsafe:              {"SOC2-CC8.1", "PCI-6.4", "CIS-16.5"},
	CheckGHActionScriptInjection:             {"SOC2-CC8.1", "PCI-6.4.1", "CIS-16.5"},
	CheckGHActionOverpermissioned:            {"SOC2-CC6.3", "PCI-7.2", "CIS-6.8"},
	CheckGHActionSecretsEchoed:               {"SOC2-CC6.1", "PCI-6.3.1", "CIS-3.7"},
	CheckGHActionSelfHostedPublic:            {"SOC2-CC6.6", "PCI-1.3", "CIS-16.5"},
	CheckGHActionWorkflowRunUnsafe:           {"SOC2-CC8.1", "PCI-6.4", "CIS-16.5"},
	CheckGHActionGitHubEnvInjection:          {"SOC2-CC8.1", "PCI-6.4.1", "CIS-16.5"},
	CheckGHActionSecretsInherit:              {"SOC2-CC6.3", "PCI-7.2", "CIS-6.8"},
	CheckGHActionInsecureCommands:            {"SOC2-CC8.1", "PCI-6.4", "CIS-16.5"},
	CheckGHActionBotConditionSpoofable:       {"SOC2-CC8.1", "CIS-16.5"},
	CheckGHActionArtiPacked:                  {"SOC2-CC8.1", "PCI-6.3.1", "CIS-16.5"},
	CheckGHActionCachePoisoning:              {"SOC2-CC8.1", "PCI-6.3", "CIS-16.5"},
	CheckGHActionUnsignedRelease:             {"SOC2-CC7.2", "PCI-6.3", "CIS-16.5"},
	CheckGHActionReusableWorkflowUnpinned:    {"SOC2-CC8.1", "PCI-6.3", "NIST-PR.IP", "CIS-16.5"},
	CheckGHActionWorkflowDispatchInjection:   {"SOC2-CC8.1", "PCI-6.4.1", "CIS-16.5"},
	CheckGHActionKnownCompromised:            {"SOC2-CC8.1", "PCI-6.3.3", "NIST-PR.IP", "CIS-16.5"},
	CheckGHActionIssueCommentUnsafe:          {"SOC2-CC8.1", "PCI-6.4", "CIS-16.5"},
	CheckGHActionAutoMerge:                   {"SOC2-CC8.1", "PCI-6.4", "CIS-16.5"},
	CheckGHActionAutoApprove:                 {"SOC2-CC8.1", "PCI-6.4", "CIS-16.5"},
	CheckGHActionScheduledWrite:              {"SOC2-CC8.1", "PCI-6.4", "CIS-16.5"},
	CheckGHActionContinueOnErrorSecurity:     {"SOC2-CC8.1", "CIS-16.5"},
	CheckGHActionMissingJobTimeout:           {"SOC2-CC8.1", "CIS-16.5"},

	// ── GitHub Actions — OIDC vs long-lived credentials ─────────────────────
	CheckGHActionAWSLongLivedKey:        {"SOC2-CC6.1", "PCI-8.3.6", "NIST-PR.AC", "CIS-5.2"},
	CheckGHActionGCPServiceAccountKey:   {"SOC2-CC6.1", "PCI-8.3.6", "NIST-PR.AC", "CIS-5.2"},
	CheckGHActionAzureCredentials:       {"SOC2-CC6.1", "PCI-8.3.6", "NIST-PR.AC", "CIS-5.2"},
	CheckGHActionNPMTokenNotOIDC:        {"SOC2-CC6.1", "PCI-8.3.6", "CIS-5.2"},
	CheckGHActionPyPITokenNotTrusted:    {"SOC2-CC6.1", "PCI-8.3.6", "CIS-5.2"},
	CheckGHActionDockerPasswordSecret:   {"SOC2-CC6.1", "PCI-8.3.6", "CIS-5.2"},
	CheckGHActionPATUsedInWorkflow:      {"SOC2-CC6.1", "PCI-8.3.1", "NIST-PR.AC", "CIS-5.2"},

	// ── GitHub Repository Configuration ─────────────────────────────────────
	CheckGitHubNoBranchProtection:      {"SOC2-CC8.1", "PCI-6.4", "CIS-16.5"},
	CheckGitHubNoSecretScanning:        {"SOC2-CC6.1", "PCI-6.3.1", "CIS-3.7"},
	CheckGitHubNoDependabot:            {"SOC2-CC6.6", "PCI-6.3.3", "CIS-7.4"},
	CheckGitHubNoSAST:                  {"SOC2-CC6.6", "PCI-6.3", "CIS-16.5"},
	CheckGitHubNoVulnAlerts:            {"SOC2-CC6.6", "PCI-6.3.3", "CIS-7.4"},
	CheckGitHubForkWorkflowApproval:    {"SOC2-CC8.1", "PCI-6.4", "CIS-16.5"},
	CheckGitHubDefaultTokenWrite:       {"SOC2-CC6.3", "PCI-7.2", "CIS-6.8"},
	CheckGitHubActionsUnrestricted:     {"SOC2-CC8.1", "PCI-6.3", "CIS-16.5"},
	CheckGitHubWebhookNoSecret:         {"SOC2-CC6.1", "PCI-6.3.1", "CIS-3.7"},
	CheckGitHubOrgMFANotRequired:       {"SOC2-CC6.1", "PCI-8.4.2", "NIST-PR.AC", "CIS-5.2"},
	CheckGitHubNoPushProtection:        {"SOC2-CC6.1", "PCI-6.3.1", "CIS-3.7"},
	CheckGitHubNoSignedCommits:         {"SOC2-CC7.2", "CIS-16.5"},
	CheckGitHubNoRequiredStatusChecks:  {"SOC2-CC8.1", "PCI-6.4", "CIS-16.5"},
	CheckGitHubNoDependencyReview:      {"SOC2-CC6.6", "PCI-6.3.3", "CIS-7.4"},
	CheckGitHubSecretInCode:            {"SOC2-CC6.1", "PCI-6.3.1", "NIST-PR.AC", "CIS-3.7"},
	CheckGitHubPrivateKeyInRepo:        {"SOC2-CC6.1", "PCI-6.3.1", "CIS-3.7"},
	CheckGitHubPackagePublic:           {"SOC2-CC6.6", "CIS-4.8"},
	CheckGitHubNoCodeowners:            {"SOC2-CC8.1", "CIS-16.5"},
	CheckGitHubNoTagProtection:         {"SOC2-CC7.2", "CIS-16.5"},
	CheckGitHubNoEnvProtection:         {"SOC2-CC8.1", "PCI-6.4", "CIS-16.5"},

	// ── CI/CD ───────────────────────────────────────────────────────────────
	CheckCICDUnpinnedAction:    {"SOC2-CC8.1", "PCI-6.3", "NIST-PR.IP", "CIS-16.5"},
	CheckCICDScriptInjection:   {"SOC2-CC8.1", "PCI-6.4", "CIS-16.5"},
	CheckCICDPwnRequest:        {"SOC2-CC8.1", "PCI-6.4", "CIS-16.5"},
	CheckCICDBroadPermissions:  {"SOC2-CC6.3", "PCI-7.2", "CIS-6.8"},
	CheckSecretsAPIKey:         {"SOC2-CC6.1", "PCI-6.3.1", "CIS-3.7"},
	CheckCICDAttackPath:        {"SOC2-CC8.1", "PCI-6.4", "CIS-16.5"},
	CheckDependencyConfusion:    {"SOC2-CC8.1", "PCI-6.3", "NIST-PR.IP", "CIS-16.5"},
	CheckVulnerableDependency:  {"SOC2-CC7.1", "PCI-6.3.3", "NIST-PR.IP", "HIPAA-164.312(a)(1)", "CIS-7.4"},
	CheckJenkinsGroovyRCE:      {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC", "CIS-4.4"},

	// ── AI / LLM Security ───────────────────────────────────────────────────
	CheckAIEndpointExposed:   {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckAIKeyExposed:        {"SOC2-CC6.1", "PCI-6.3.1", "CIS-3.7"},
	CheckAIStreamingOpen:     {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckAIPromptInjection:   {"SOC2-CC6.6", "PCI-6.4.1", "CIS-16.2"},
	CheckAISystemLeak:        {"SOC2-CC6.1", "CIS-3.7"},
	CheckAISSRFViaPLLM:       {"SOC2-CC6.6", "PCI-6.4.1", "NIST-PR.AC", "CIS-16.2"},
	CheckAIDataExfil:         {"SOC2-CC6.1", "PCI-3.4", "HIPAA-164.312", "CIS-3.7"},
	CheckAIToolAbuse:         {"SOC2-CC6.6", "PCI-6.4.1", "CIS-16.2"},
	CheckAIIndirectInjection: {"SOC2-CC6.6", "PCI-6.4.1", "CIS-16.2"},

	// ── Wireless ────────────────────────────────────────────────────────────
	CheckNetDeviceUniFiExposed:   {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},
	CheckCVEUniFiLog4Shell:       {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckNetDeviceTPLinkOmada:    {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckCVETPLinkOmadaRCE:      {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckNetDeviceArubaInstant:   {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckNetDeviceOpenWRTExposed: {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckPortRADIUSExposed:       {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC", "CIS-4.4"},
	CheckWiFiOpenNetwork:         {"PCI-1.3", "SOC2-CC6.6", "NIST-PR.AC", "ISO27001-A.13.1"},
	CheckWiFiWEPNetwork:          {"PCI-4.2.1", "SOC2-CC6.7", "NIST-PR.DS", "ISO27001-A.13.1"},
	CheckWiFiWPSEnabled:          {"PCI-4.2.1", "SOC2-CC6.7", "NIST-PR.AC"},
	CheckWiFiWPA2TKIP:            {"PCI-4.2.1", "SOC2-CC6.7"},
	CheckWiFiGatewayExposed:      {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC"},
	CheckWiFiPMKID:               {"PCI-4.2.1", "SOC2-CC6.7", "NIST-PR.DS"},

	// ── Network device BMC exposure ─────────────────────────────────────────
	CheckNetDeviceBMCExposed: {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC", "CIS-4.4"},

	// ── Web3 / Blockchain ───────────────────────────────────────────────────
	CheckWeb3RPCEndpointExposed:   {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckContractReentrancy:       {"SOC2-CC6.6", "CIS-16.2"},
	CheckContractSelfDestruct:     {"SOC2-CC6.6", "CIS-16.2"},
	CheckContractUncheckedCall:    {"SOC2-CC6.6", "CIS-16.2"},
	CheckContractIntegerOverflow:  {"SOC2-CC6.6", "CIS-16.2"},
	CheckContractProxyAdmin:       {"SOC2-CC6.3", "CIS-6.8"},
	CheckChainNodeRPCExposed:      {"SOC2-CC6.6", "PCI-1.3", "CIS-4.4"},
	CheckChainNodeUnauthorized:    {"SOC2-CC6.2", "PCI-1.3", "NIST-PR.AC", "CIS-5.2"},
	CheckWeb3SIWEDomainBypass:     {"SOC2-CC6.6", "PCI-6.4.1", "CIS-16.2"},
	CheckWeb3SIWENonceReuse:       {"SOC2-CC6.6", "NIST-PR.AC", "CIS-16.2"},
	CheckWeb3SIWEReplay:           {"SOC2-CC6.6", "NIST-PR.AC", "CIS-16.2"},
	CheckWeb3SIWEOverHTTP:         {"SOC2-CC6.7", "PCI-4.2.1", "CIS-3.10"},
	CheckWeb3HorizontalEscalation: {"SOC2-CC6.3", "PCI-7.2", "NIST-PR.AC", "CIS-6.8"},

	// ── Gateway / CDN / Infrastructure ──────────────────────────────────────
	CheckGatewayKongAdminExposed:    {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC", "CIS-4.8"},
	CheckGatewayKongRouteEnum:       {"SOC2-CC6.6", "CIS-4.8"},
	CheckGatewayHAProxyStatsExposed: {"SOC2-CC6.6", "PCI-1.3", "CIS-4.8"},
	CheckGatewayNginxStatusExposed:  {"SOC2-CC6.6", "CIS-4.8"},
	CheckGatewayVarnishDebugExposed: {"SOC2-CC6.6", "CIS-4.8"},
	CheckGatewayTraefikAPIExposed:   {"SOC2-CC6.6", "PCI-1.3", "CIS-4.8"},
	CheckGatewayEnvoyAdminExposed:   {"SOC2-CC6.6", "PCI-1.3", "CIS-4.8"},
	CheckGatewayLinkerdVizExposed:   {"SOC2-CC6.6", "PCI-1.3", "CIS-4.8"},
	CheckGatewayF5AdminExposed:      {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC", "CIS-4.8"},
	CheckGatewayCitrixAdminExposed:  {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC", "CIS-4.8"},
	CheckGatewayTykDashExposed:      {"SOC2-CC6.6", "PCI-1.3", "CIS-4.8"},
	CheckCDNVarnishPurgeEnabled:     {"SOC2-CC6.6", "CIS-4.8"},

	// ── Cloud — GCP ─────────────────────────────────────────────────────────
	CheckCloudGCPIAMPrimitiveRole:     {"SOC2-CC6.3", "PCI-7.2", "NIST-PR.AC", "ISO27001-A.9.2", "CIS-6.8"},
	CheckCloudGCPServiceAccountKey:    {"SOC2-CC6.1", "PCI-8.3.1", "NIST-PR.AC", "CIS-5.2"},
	CheckCloudGCPServiceAccountKeyOld: {"SOC2-CC6.1", "PCI-8.3.6", "NIST-PR.AC", "CIS-5.2"},
	CheckCloudGCPBucketPublic:         {"SOC2-CC6.6", "PCI-1.3", "HIPAA-164.312(a)(1)", "NIST-PR.DS", "CIS-3.3"},
	CheckCloudGCPComputeDefaultSA:     {"SOC2-CC6.3", "PCI-7.2", "NIST-PR.AC", "CIS-6.8"},
	CheckCloudGCPGKEPublicEndpoint:    {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC", "CIS-4.4"},
	CheckCloudGCPGKENoBinaryAuth:      {"SOC2-CC7.2", "PCI-6.3", "NIST-PR.DS", "CIS-16.5"},

	// ── Cloud — AWS ─────────────────────────────────────────────────────────
	CheckCloudAWSIAMRootAccessKey:  {"SOC2-CC6.1", "PCI-8.3.1", "NIST-PR.AC", "ISO27001-A.9.2", "CIS-5.4"},
	CheckCloudAWSIAMRootNoMFA:      {"SOC2-CC6.1", "PCI-8.4.2", "NIST-PR.AC", "ISO27001-A.9.4", "CIS-6.5"},
	CheckCloudAWSIAMUserNoMFA:      {"SOC2-CC6.1", "PCI-8.4.2", "NIST-PR.AC", "CIS-6.5"},
	CheckCloudAWSIAMAccessKeyOld:   {"SOC2-CC6.1", "PCI-8.3.6", "NIST-PR.AC", "CIS-5.2"},
	CheckCloudAWSIAMPolicyWildcard: {"SOC2-CC6.3", "PCI-7.2", "NIST-PR.AC", "ISO27001-A.9.2", "CIS-6.8"},
	CheckCloudAWSS3BucketPublic:    {"SOC2-CC6.6", "PCI-1.3", "HIPAA-164.312(a)(1)", "NIST-PR.DS", "CIS-3.3"},
	CheckCloudAWSS3NoEncryption:    {"SOC2-CC6.1", "PCI-3.5", "HIPAA-164.312(a)(2)", "NIST-PR.DS", "CIS-3.11"},
	CheckCloudAWSEC2PublicSG:       {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC", "CIS-4.4"},
	CheckCloudAWSEKSPublicEndpoint: {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC", "CIS-4.4"},

	// ── Cloud — Azure ───────────────────────────────────────────────────────
	CheckCloudAzureBlobPublic:        {"SOC2-CC6.6", "PCI-1.3", "HIPAA-164.312(a)(1)", "NIST-PR.DS", "CIS-3.3"},
	CheckCloudAzureStorageHTTP:       {"SOC2-CC6.7", "PCI-4.2.1", "HIPAA-164.312(e)(2)", "NIST-PR.DS", "CIS-3.10"},
	CheckCloudAzureAKSPublicEndpoint: {"SOC2-CC6.6", "PCI-1.3", "NIST-PR.AC", "CIS-4.4"},
	CheckCloudAzureOwnerDirect:       {"SOC2-CC6.3", "PCI-7.2", "NIST-PR.AC", "ISO27001-A.9.2", "CIS-6.8"},

	// ── WHOIS ───────────────────────────────────────────────────────────────
	CheckWHOISDomainExpiry7d:  {"SOC2-CC9.1", "CIS-12.1"},
	CheckWHOISDomainExpiry30d: {"SOC2-CC9.1", "CIS-12.1"},

	// ── CMS ─────────────────────────────────────────────────────────────────
	CheckCMSPluginVulnerable: {"PCI-6.3.3", "SOC2-CC6.6", "CIS-7.4"},

	// ── CVEs — all KEV/critical vulnerabilities ─────────────────────────────
	// Pattern: unpatched CVE → PCI-6.3.3 (patch management) + SOC2-CC6.6 (vuln mgmt)
	// RCE CVEs also get NIST-PR.IP (information protection)
	CheckCVELog4Shell:                {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEN8nRCE:                   {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVECraftCMSRCE:              {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVELivewireRCE:              {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEBeyondTrustRCE:           {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVENginxUIBackup:            {"PCI-6.3.3", "SOC2-CC6.6", "CIS-7.4"},
	CheckCVESolarWindsWHD:            {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEIvantiEPMAuthBypass:      {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVELangflowRCE:              {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEOmnissaSSRF:              {"PCI-6.3.3", "SOC2-CC6.6", "CIS-7.4"},
	CheckCVEKeycloakSAMLBypass:       {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.AC", "CIS-7.4"},
	CheckCVEStruts2S2066:             {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVERailsXMLRCE:              {"PCI-6.3.3", "SOC2-CC6.6", "CIS-7.4"},
	CheckCVEHFSRejetto:               {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEManageEngineServiceDesk:  {"PCI-6.3.3", "SOC2-CC6.6", "CIS-7.4"},
	CheckCVEMinIOEnvDisclosure:       {"SOC2-CC6.1", "PCI-6.3.1", "HIPAA-164.312(a)(1)", "CIS-7.4"},
	CheckCVEOllamaPathTraversal:      {"PCI-6.3.3", "SOC2-CC6.6", "CIS-7.4"},
	CheckCVEFortiOSWSAuthBypass:      {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEIvantiCS2025:             {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVESAPNetWeaver2025:         {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEIvantiEPMMRCE:            {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVECiscoFMCRCE:              {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEHPEOneViewRCE:            {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVECitrixBleed2:             {"PCI-6.3.3", "SOC2-CC6.6", "CIS-7.4"},
	CheckCVEFortiOSSSOBypass:         {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.AC", "CIS-7.4"},
	CheckCVEFortiWebAuthBypass:       {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVECiscoASARCE:              {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEMCPServerExposed:         {"PCI-6.3.3", "SOC2-CC6.6", "CIS-7.4"},
	CheckCVEErlangOTPSSH:             {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEVeeamBackupExposed:       {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVESupersetDefaultKey:       {"PCI-6.3.3", "SOC2-CC6.6", "CIS-7.4"},
	CheckCVEMLflowAuthBypass:         {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.AC", "CIS-7.4"},
	CheckCVEHarborDefaultCreds:       {"PCI-6.3.3", "SOC2-CC6.2", "NIST-PR.AC", "CIS-7.4"},
	CheckCVEGrafanaPathTraversal:     {"PCI-6.3.3", "SOC2-CC6.6", "CIS-7.4"},
	CheckCVEZabbixSessionForge:       {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.AC", "CIS-7.4"},
	CheckCVEpgAdminValidateRCE:       {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEGiteaCMDInjection:        {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEAirflowDAGRCE:            {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVELibupnpSSDPRCE:           {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckPortJuniperAnomalyExposed:   {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckPortTelnetdVulnerable:       {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVETelnetBSDEncrypt:         {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckPortFTPWingRCE:              {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckPortRedisVulnerableCVE2025:  {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckPortKibanaVulnerable:        {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP"},
	CheckCVENextJSMiddlewareBypass:   {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.AC", "CIS-7.4"},
	CheckCVEViteFileRead:             {"PCI-6.3.3", "SOC2-CC6.6", "CIS-7.4"},
	CheckCVEIngressNightmare:         {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVETomcatPartialPUT:         {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEOpenSSHRegreSSHion:       {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEJenkinsCLIFileRead:       {"PCI-6.3.3", "SOC2-CC6.6", "CIS-7.4"},
	CheckCVEScreenConnectBypass:      {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVETeamCityAuthBypass:       {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.AC", "CIS-7.4"},
	CheckCVEFortiManagerJump:         {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEPHPCGIArgInjection:       {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEExpeditionRCE:            {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEFortiOSSSLVPN:            {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVECheckPointFileRead:       {"PCI-6.3.3", "SOC2-CC6.6", "CIS-7.4"},
	CheckCVESharePointJWT:            {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.AC", "CIS-7.4"},
	CheckCVEOwnCloudPhpInfo:          {"PCI-6.3.3", "SOC2-CC6.6", "CIS-7.4"},
	CheckCVEMOVEitWebShell:           {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEConfluenceSetup:          {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEConfluenceRestore:        {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVECiscoIOSXEImplant:        {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEIvantiConnectSecure:      {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.AC", "CIS-7.4"},
	CheckCVEIvantiCMDInjection:       {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVECitrixBleed:              {"PCI-6.3.3", "SOC2-CC6.6", "CIS-7.4"},
	CheckCVECitrixADCRCE2023:         {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEJuniperJWeb:              {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEJuniperJWeb2024:          {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVESysAid:                   {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVETeamCityRPC2:             {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.AC", "CIS-7.4"},
	CheckCVETeamCityDirTraversal:     {"PCI-6.3.3", "SOC2-CC6.6", "CIS-7.4"},
	CheckCVEBarracudaESG:             {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEOpenfire:                 {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.AC", "CIS-7.4"},
	CheckCVECiscoASASSLVPN:           {"PCI-6.3.3", "SOC2-CC6.6", "CIS-7.4"},
	CheckCVERoundcube:                {"PCI-6.3.3", "SOC2-CC6.6", "CIS-7.4"},
	CheckCVEF5BigIPAuthBypass:        {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEConfluenceOGNL:           {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEFortiOSAuthBypass:        {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.AC", "CIS-7.4"},
	CheckCVEVMwareWorkspaceONE:       {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEWSO2FileUpload:           {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVESpring4Shell:             {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEZimbraAuthBypass:         {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.AC", "CIS-7.4"},
	CheckCVESophosFW:                 {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEManageEngineSAML:         {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEMagentoRCE:               {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEOracleEBS:                {"PCI-6.3.3", "SOC2-CC6.6", "CIS-7.4"},
	CheckCVEExchangeProxyLogon:       {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEExchangeProxyShell:       {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEvCenterExposed:           {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEApacheHTTPTraversal:      {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEGitLabRCE:                {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVESaltStackAPI:             {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEAccellionFTA:             {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEManageEngineADSelfSvc:    {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVESonicWallSMAExposed:      {"PCI-6.3.3", "SOC2-CC6.6", "CIS-7.4"},
	CheckCVEF5BigIPTMUI:              {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEWebLogicConsole:          {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVECitrixADCInfo:            {"PCI-6.3.3", "SOC2-CC6.6", "CIS-7.4"},
	CheckCVESolarWindsOrion:          {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEApacheUnomi:              {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVELiferayRCE:               {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEMobileIronRCE:            {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEvBulletin5xRCE:           {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEPulseSecureVPN:           {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEPANGlobalProtect:         {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEPANGlobalProtectCMD:      {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVECrowdPdkInstall:          {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.AC", "CIS-7.4"},
	CheckCVETelerikRAU:               {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEWebLogicAsync:            {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVESolrAdminExposed:         {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEEximRCE2019:              {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEDLinkHNAP:                {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEDrupalgeddon2:            {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEManageEngineDesktopCVE:   {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEKubernetesPrivEsc:        {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.AC", "CIS-7.4"},
	CheckCVEJenkinsStaplerRCE:        {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEEximHeapOverflow:         {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEApacheTikaRCE:            {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEFortiOSCredLeak:          {"PCI-6.3.3", "SOC2-CC6.6", "CIS-7.4"},
	CheckCVEColdFusionFCKEditor:      {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEStruts2OGNL:              {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEWebLogicWLSWSAT:          {"PCI-6.3.3", "SOC2-CC6.6", "NIST-PR.IP", "CIS-7.4"},
	CheckCVEHikvisionISAPI:           {"PCI-6.3.3", "SOC2-CC6.6", "CIS-7.4"},
	CheckCVEOpenSSHUsernameEnum:      {"PCI-6.3.3", "SOC2-CC6.6", "CIS-7.4"},

	// ── Cookie Security ─────────────────────────────────────────────────
	CheckCookieNoPrefix:       {"SOC2-CC6.1", "PCI-6.5.10", "CIS-16.1"},
	CheckCookieExcessiveScope: {"SOC2-CC6.1", "PCI-6.5.10", "CIS-16.1"},

	// ── CSP Bypass ──────────────────────────────────────────────────────
	CheckCSPDataURI:        {"SOC2-CC6.1", "PCI-6.5.7", "NIST-PR.DS", "CIS-16.1"},
	CheckCSPBaseURIMissing: {"SOC2-CC6.1", "PCI-6.5.7", "CIS-16.1"},
	CheckCSPFrameAncestors: {"SOC2-CC6.1", "PCI-6.5.7", "CIS-16.1"},
	CheckCSPObjectSrc:      {"SOC2-CC6.1", "PCI-6.5.7", "CIS-16.1"},
	CheckCSPReportOnly:     {"SOC2-CC6.1", "CIS-16.1"},

	// ── NTLM ────────────────────────────────────────────────────────────
	CheckNTLMInfoLeak: {"SOC2-CC6.1", "PCI-2.2.2", "NIST-PR.AC", "CIS-3.3"},

	// ── HTTP/2 ──────────────────────────────────────────────────────────
	CheckHTTP2ContinuationFlood: {"SOC2-CC7.1", "PCI-6.5.2", "NIST-PR.DS", "CIS-13.6"},

	// ── API Security ────────────────────────────────────────────────────
	CheckAPIBOLA:           {"SOC2-CC6.1", "PCI-6.5.8", "NIST-PR.AC", "CIS-14.6"},
	CheckAPIMassAssignment: {"SOC2-CC6.1", "PCI-6.5.8", "CIS-14.6"},
	CheckAPINoRateLimit:    {"SOC2-CC6.1", "PCI-6.5.2", "CIS-13.6"},

	// ── Subdomain Discovery ─────────────────────────────────────────────
	CheckSubdomainPermutation: {"SOC2-CC7.1", "CIS-12.1"},
	CheckSubdomainBruteforce:  {"SOC2-CC7.1", "CIS-12.1"},

	// ── OOB Callback ────────────────────────────────────────────────────
	CheckOOBCallbackReceived: {"SOC2-CC6.6", "PCI-6.5.1", "NIST-PR.DS", "CIS-16.1"},
}
